### ISSUE TITLE
Please move to ng-template to support ng4

### ISSUE THREAD

**Issue by isaacplmann** [isaacplmann/ngx-contextmenu#1]
_From @born2net on March 26, 2017 1:40_

Please move to ```<ng-template/>``` to support ng4
tx

Sean

_Copied from original issue: isaacplmann/angular2-contextmenu#60_

**Comment by isaacplmann** [comment]
Yes, thanks for the reminder.  I'll shoot for the end of the week.

**Comment by isaacplmann** [comment]
_From @born2net on March 27, 2017 13:12_

great tx!

**Comment by isaacplmann** [comment]
Fixed with the rename to ngx-contextmenu.

**Comment by isaacplmann** [comment]
_From @born2net on March 31, 2017 20:50_

do we need to change anything in the code?

**Comment by isaacplmann** [comment]
Yeah, there are some breaking changes.  See https://github.com/isaacplmann/ngx-contextmenu.  Documentation is a bit sparse now.  I'll try to write more through upgrade steps on Monday.

**Comment by isaacplmann** [comment]
_From @born2net on March 31, 2017 20:52_

great will look fwd to it.. TX!!!!
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by isaacplmann** [comment]
Upgrade documentation now in readme.

**Comment by born2net** [comment]
tx!!!

**Comment by born2net** [comment]
In latest version from today  when I make a selection on the context menu, the context menu does not close.
Should I open a separate bug?

**Comment by isaacplmann** [comment]
Yes, separate bug please.  The context menu is closing for me.
