### ISSUE TITLE
Context menus are not created for components initialized at startup

### ISSUE THREAD

**Issue by Anthony-Breneliere** [isaacplmann/ngx-contextmenu#100]
Hello,

I have a list of buttons with a ngx-contextmenu for each of them.

Context menus are pretty well displayed when buttons are created in the DOM while the application is already launched.

But if buttons are created in the DOM at startup, for example in the case I launch my application with a specific route that load my buttons, then there is not ngx-contextmenu in the DOM.

I use angular 5.2.9 with ngx-contextmenu 4.1.2.

It is as if something context menu service had not finished to initialize when the buttons are created at startup, so context menu items are not added.

Did I miss something ?

DOM for buttons that are created AFTER the application is launched:
```
<div class="cdk-overlay-container"><div id="cdk-overlay-12" class="cdk-overlay-pane ngx-contextmenu" dir="ltr" style="pointer-events: auto; top: 189px; left: 117px;"><context-menu-content _nghost-c12=""><div _ngcontent-c12="" class="dropdown open show ngx-contextmenu" tabindex="0">
      <ul _ngcontent-c12="" class="dropdown-menu show" style="position: static; float: none;" tabindex="0">
        <li _ngcontent-c12="">
        </li><li _ngcontent-c12="">
        </li><li _ngcontent-c12="">
        </li>
      </ul>
    </div>
  </context-menu-content></div></div>
```

DOM for buttons that are created at startup:
```
<div class="cdk-overlay-container"><div id="cdk-overlay-18" class="cdk-overlay-pane ngx-contextmenu" dir="ltr" style="pointer-events: auto;"><context-menu-content _nghost-c12=""><div _ngcontent-c12="" class="dropdown open show ngx-contextmenu" tabindex="0">
      <ul _ngcontent-c12="" class="dropdown-menu show" style="position: static; float: none;" tabindex="0">
        <!---->
      </ul>
    </div>
  </context-menu-content></div></div>
```

**Comment by isaacplmann** [comment]
What does your template look like that declares your `<context-menu>` component?

**Comment by isaacplmann** [comment]
Can you show me some of the actual code? My guess is that you have an
`*ngFor` that is looping over something asynchronous to generate your
context menu items.

**Comment by isaacplmann** [comment]
You may need to do something similar to what @sherlock1982 did in #95.  Wrapping your `this.contextMenuService.show.next` call in a `setTimeout`.

**Comment by Anthony-Breneliere** [comment]
Hello,

I tried to delay the menu display. So I added (contextMenu)="delayContextMenuDisplay( $event, intervention )", but I don't know why the event contextMenu is never fired.

```
<div *ngIf="intervention" routerLink="/intervention/{{intervention.Id}}" queryParamsHandling="preserve" [class.borderhalo]="updating" [class.defaultBorder]="!updating" class="bouton_intervention transition_1s" [class.unselected]="selected !== true" [class.selected]="selected === true"
    (click)="onClickInter()" (contextMenu)="delayContextMenuDisplay( $event, intervention )" [ngClass]="{buttonMenu:buttonMenu.isShown}">
```

```
    public delayContextMenuDisplay($event: MouseEvent, intervention: Intervention): void {

        console.log( "show context menu for " + intervention.Id);

        setTimeout(() => {
            console.log( "show context menu for " + intervention.Id);

            this.contextMenuService.show.next({
                // Optional - if unspecified, all context menu components will open
                contextMenu: this.buttonMenu,
                event: $event,
                item: intervention,
            } );
        }, 5000 ); 
    }
```
I don't see logs show context menu for " + intervention.Id.

**Comment by isaacplmann** [comment]
(contextmenu) should have a lowercase m.

**Comment by Anthony-Breneliere** [comment]
Yes with (contextmenu) in lowercase the event is fired but the menu is either not displayed, or it is hidden by the classic browser context menu that is displayed instead.

in .ts

> @ViewChild(ContextMenuComponent) public buttonMenu: ContextMenuComponent;

in .html:

> <context-menu #buttonMenu>

**Comment by isaacplmann** [comment]
You have to call `$event.preventDefault()` inside `delayContextMenuDisplay` before the `setTimeout`.

**Comment by isaacplmann** [comment]
I think `$event.stopPropagation()` is not necessary, but try adding that if the context menu still doesn't show.

**Comment by Anthony-Breneliere** [comment]
Adding a delay for displaying the context menu does not work. The context menu is not displayed.

When the button that holds the [contextMenu] or (contextMenu) attribute is created, the context menu does not seem to be linked to the component, as if there was no [contextMenu] attribute.

But if I hide and display the button again, then the context menu is displayed.

**Comment by vgordievskiy** [comment]
I have found workaround for this problem:
```typescript
this.contextMenuService.show.subscribe((el) => {
   const overlay = this.contextMenuService.getLastAttachedOverlay();
   overlay.updatePosition();
   const comp: any = overlay.contextMenu;
   comp.changeDetector.markForCheck();
   comp.changeDetector.detectChanges();
})
```

**Comment by Anthony-Breneliere** [comment]
The workaround is perfect (works with 5.0.1). 

And there is no need to have a delayContextMenuDisplay(  ) method that did not change anything.
The component that support context menu can use attributes [contextMenu]="" [contextMenuSubject]="".
