### ISSUE TITLE
Violation warning in console

### ISSUE THREAD

**Issue by Jamlearner** [isaacplmann/ngx-contextmenu#107]
> [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>

This is nothing important but I see this warning showing up in my app. But when I checked the demo, it does not have this issue. Is there anything I can remove this warning? Or fix it in my app? I do not understand why is this warning.

**Comment by isaacplmann** [comment]
I’m not sure what the problem is.  I quick google search showed this issue: https://github.com/angular/material2/issues/4221

**Comment by Jamlearner** [comment]
My mistake. Not a ngx-contextmenu issue. Thank you!
