### ISSUE TITLE
Angular 6 : will we get an updated version ?

### ISSUE THREAD

**Issue by msegmx** [isaacplmann/ngx-contextmenu#111]
When I issue the command :

`ng update @angular/cdk`
I get :
`Package "ngx-contextmenu" has an incompatible peer dependency to "@angular/cdk" (requires "^5.0.0-rc0 || ^5.0.0-rc.1 || ^5.0.0-rc.2 ||^5.0.0", would install "6.0.0").`

Will we get an updated version of ngx-contextmenu ?

**Comment by isaacplmann** [comment]
Yes.  Thanks to @czeckd for the PR.  I'll merge and release a new version today or tomorrow.
