### ISSUE TITLE
menu does not seem to position correctly with <ul>

### ISSUE THREAD

**Issue by gjenner** [isaacplmann/ngx-contextmenu#12]
![contextmenu](https://cloud.githubusercontent.com/assets/25956637/25010763/14e58c78-2039-11e7-8b47-9864b8895479.png)

**Comment by isaacplmann** [comment]
There should be a `<context-menu-content>` element attached to the root element of your angular app.  Is it there?

Inside that element is a `div.ngx-contextmenu` and then `ul.dropdown-menu`.  What are the styles on the `ul.dropdown-menu`?  Is menu positioned correctly if you change `ul.dropdown-menu` from `position:fixed` to `position:absolute`?

**Comment by gjenner** [comment]
On your GitHub, I am not seeing the  <context-menu-content>

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
It only appears when a context menu is actually open.  And you can see it in the demo under:

html > body > ngx-context-menu-demo > context-menu-content

(It's the last child node of ngx-context-menu-demo.)

**Comment by gjenner** [comment]
Not seeing it, and I am getting Template parse warning in the console

The <template> element is deprecated. Use <ng-template> instead

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Look at this demo: https://isaacplmann.github.io/ngx-contextmenu/
Not the angular2-contextmenu one.

**Comment by gjenner** [comment]
I am looking at that one, migrating up from angular 2.  Is there something you see I am doing incorrectly?

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Wherever you are using <template> use <ng-template> instead.  Of course, that error could be coming from a library that you're using in which case you won't be able to make it go away.

I'll need to see your code to help more.

**Comment by gjenner** [comment]
So you are able to make the Angular 4 context menu work with *ngFor?

Is it not weird it have the menu in the two places?  I would think that hint would help, but I understand

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Yes, the demo code uses *ngFor.  What version of ngx-contextmenu are you using?

**Comment by gjenner** [comment]
Where would I find this? in the package.json I manually changed it to ngx-contextmenu, but did not change the version number from ^0.8.1

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
The latest version is 1.0.3.  You can change your version to "^1.0.3" in package.json.  To see what you currently have installed, you can look in node_modules/ngx-contextmenu/package.json.  Or you can run `npm outdated` from a command line to get a list of all dependencies that aren't on the latest version.

**Comment by gjenner** [comment]
Thank you, it states “version”: “1.0.3”

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Ok.  I'll need to see some of your code or a sample repo to help more.

**Comment by gjenner** [comment]
I fan the outdated, It did not have the ngx-contextmenu in the list, just the angular2-contextmenu

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
Should I uninstall the angular2-contextmenu?

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Yes, angular2-contextmenu will just confuse things.

**Comment by gjenner** [comment]
Not sure how to do that, it is so intertwined.  You could come online if you wish, maybe Skype?

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
It just seems like I am missing something.  

The menu is not pretty, blue hyperlinks

When I add the class=”dropdown ngx-contextmenu” and the class=”dropdown-menu” (with the css in the style page), the bad menu just disappears.  Could there be a component not installing, or some remanence of the previous version (which I did uninstall)

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
We also use Primeng controls (datagrid and table), but their package also has a ContextMenuModlue, do you think there might be something there?

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
So I have created two menu, one in HTML, and the other using *ngFor ul.

The HTML one appears correctly positioned (the styling is a blue hyperlink, but that is for another discussion).  The *ngFor displays the list outside of the component as a list, even though I have <li [contextMenu] = “cmMenu” [contextMenuSubject]=”item”

 

Also a reminder, in the console I am getting 

The <template> element is deprecated.  Use <ng-template> instead (“Warning _>] <template ngFor [ngForOf] = “parts”…

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Show me what snippets of your template and code.  I can’t help if I can’t see what you’re doing.

**Comment by gjenner** [comment]
***************** menu's, outside of the main HTML ***************** 

<div>

  <ul [contextMenu]="cmNew" [contextMenuSubject]="item">

    <li *ngFor="let item of cmMenuItems"  (click)="onContextMenuItemSelected($event, item)">{{item?.name}}

      <context-menu #cmNew>

      </context-menu>

    </li>

  </ul>

</div>

<div>

  <context-menu #cmNew2>

    <ng-template contextMenuItem (execute)="showMessage('Hi, ' + $event.item.name)">

      Say hi!

    </ng-template>

  </context-menu>

</div>

 

 

***************** where the click event is  ***************** 

            <p-dataTable [value]="ocDiagnosisSelected" [resizableColumns]="true" selectionMode="single" [(selection)]="oDiagnosisSelected"

              (onRowSelect)="onSelectedDiagnosisRowSelect($event)">

              <p-column field="OrganizationInternalCode" header="Code" [style]="{'width':'150px'}"></p-column>

              <p-column field="Description" header="Description" [style]="{'width':'500px'}"></p-column>

              

            </p-dataTable>

 

***************** populate list  ***************** 

  onSelectedDiagnosisRowSelect($event): void {

    this.boolChronicSelected = false;

    let me: MouseEvent = $event.originalEvent;

 

    let eventData: any = $event;

    this.intSelectedRow = eventData.rowIndex;

    this.cmMenuItems = new Array<any>();

    this.cmAddMenuItem(0, "", "item 1");

    this.cmAddMenuItem(0, "", "item 2 ");

    this.cmAddMenuItem(0, "", "item 3 ");

    this.cmAddMenuItem(0, "", "Remove");

 

 

    if (this.cmMenuItems.length !== 0) {

      this.contextMenuService.show.next({

        // Optional - if unspecified, all context menu components will open

        contextMenu: this.cmNew,

        event: me,

        item: this.oDiagnosisSelected,

      });

 

 

    };

  };

  cmAddMenuItem(intIDENTITY: number, strCode: string, strDescription: string): void {

    let cd: CodeDescription = new CodeDescription;

    cd.IDENTITY = intIDENTITY;

    cd.Code = strCode;

    cd.Description = strDescription

    let cmMenuItem: any = {};

    cmMenuItem = {

      name: cd.Description,

      CodeDescription: cd

      // html: () => cd.Description,

      // click: () => { this.onContextMenuItemSelected(strDescription, cd); }

    };

    this.cmMenuItems.push(cmMenuItem);

  };

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
Oh, I moved the [contextMenu] and the [contextMenuItem] back into the <li>, this was just a test

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
See [usage](https://github.com/isaacplmann/ngx-contextmenu#template).

1. `[contextMenu]` and `[contextMenuSubject]` should go on the `<li>`. (You did this.)
2. `cmNew` is a blank context menu.  You should have `[contextMenu]="cmNew2"` if you want to use that one.
3. Using `[contextMenu]` and `[contextMenuSubject]` is an alternative to manually triggering the context menu in your `onContextMenuItemSelected` method.  You don't need both - and they might conflict with each other.

What does your `onContextMenuItemSelected` method look like?

**Comment by gjenner** [comment]
cmNew is being populated by the code behind.  The cmNew2 is just to see the HTML menu displayed correctly.  The cmNew2 is not valid, and deleted

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
And your demo source shows both [contextMenu] and [contextMenuSubject]

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
1. cmNew is not being populated unless there's some code I don't know about.
2. There are 2 options for triggering a context menu (1) use `[contextMenu]` and `[contextMenuSubject]` or (2) manually trigger in some function use `contextMenuService.show.next()`.  You probably don't want to use them both at the same time.

**Comment by gjenner** [comment]
OK, I see, I thought the <ul> polulated the menu.  Adding the actions is necessart to work, even though I do not use them

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
So there are two arrays, one is the items and the other is the actions.  They MUST be in the same order, while the actions can have “dividers” randomly throughout, making the arrays not align by index, correct?

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
`items` is the list of whatever you are acting on in your application.  It could be a list of appointments in your case.
`actions` is the list of options in the context menu - they correspond directly to `contextMenuItem`s.  And you'll need to use an `*ngFor` to make `<ng-template contextMenuItem>`s from your `actions` object.  See [this example](https://github.com/isaacplmann/ngx-contextmenu#dynamic-context-menu).

**Comment by gjenner** [comment]
Same result with below

 

***************** menu's, outside of the main HTML ***************** 

<div>

  <ul>

    <li *ngFor="let item of cmMenuItems" [contextMenu]="cmNew" (click)="onContextMenuItemSelected($event, item)">{{item?.name}}

      <context-menu #cmNew>

        <template *ngFor="let action of item.cmMenuActions" contextMenuItem let-item [visible]="action.visible" [enabled]="action.enabled"

          [divider]="action.divider" (execute)="action.execute($event.item)">

          {{ action.html(item) }}

        </template>

      </context-menu>

    </li>

  </ul>

</div>

 

 

***************** where the click event is  ***************** 

            <p-dataTable [value]="ocDiagnosisSelected" [resizableColumns]="true" selectionMode="single" [(selection)]="oDiagnosisSelected"

              (onRowSelect)="onSelectedDiagnosisRowSelect($event)">

              <p-column field="OrganizationInternalCode" header="Code" [style]="{'width':'150px'}"></p-column>

              <p-column field="Description" header="Description" [style]="{'width':'500px'}"></p-column>

              

            </p-dataTable>

 

***************** populate list  ***************** 

  onSelectedDiagnosisRowSelect($event): void {

    this.boolChronicSelected = false;

    let me: MouseEvent = $event.originalEvent;

 

    let eventData: any = $event;

    this.intSelectedRow = eventData.rowIndex;

    this.cmMenuItems = new Array<any>();

    this.cmAddMenuItem(0, "", "item 1");

    this.cmAddMenuItem(0, "", "item 2");

    this.cmAddMenuItem(0, "", "item 3");

    this.cmAddMenuItem(0, "", "Remove");

 

 

    if (this.cmMenuItems.length !== 0) {

      this.contextMenuService.show.next({

        // Optional - if unspecified, all context menu components will open

        contextMenu: this.cmNew,

        event: me,

        item: this.oDiagnosisSelected,

      });

 

 

    };

  };

cmAddMenuItem(intIDENTITY: number, strCode: string, strDescription: string): void {

    let cd: CodeDescription = new CodeDescription;

    cd.IDENTITY = intIDENTITY;

    cd.Code = strCode;

    cd.Description = strDescription

    let cmMenuItem: any = {};

    cmMenuItem = {

      name: cd.Description,

      CodeDescription: cd,

      // html: () => cd.Description,

      // click: () => { this.onContextMenuItemSelected(strDescription, cd); }

    };

    this.cmMenuItems.push(cmMenuItem);

    let cmMenuAction: any = {};

    cmMenuAction = {

      html: (item) => cd.Description,

      visible: (item) => true,

      enabled: (item) => true,

      // html: () => cd.Description,

      // click: () => { this.onContextMenuItemSelected(strDescription, cd); }

    };

    this.cmMenuActions.push(cmMenuAction);

 

  };

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
What does your `onContextMenuItemSelected` method look like?

**Comment by gjenner** [comment]
Actually, that part works, I just have to find the menu

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
You are very responsive, thank you.

Any suggestions at this time?

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
I haven't seen any of your code that would trigger the context menu.  If it's not in the `onContextMenuItemSelected` method, I need to know where you're triggering the context menu.  What do you right-click on to get the context menu to appear?

**Comment by gjenner** [comment]
I trigger the menu with a left click on the table.  

 

<p-dataTable [value]="ocDiagnosisSelected" [resizableColumns]="true" selectionMode="single" [(selection)]="oDiagnosisSelected" (onRowSelect)="onSelectedDiagnosisRowSelect($event)"> 

<p-column field="OrganizationInternalCode" header="Code" [style]="{'width':'150px'}"></p-column> 

<p-column field="Description" header="Description" [style]="{'width':'500px'}"></p-column> 

</p-dataTable>

 

Then I populate the arrays

 

onSelectedDiagnosisRowSelect($event): void { 

let me: MouseEvent = $event.originalEvent; 

let eventData: any = $event; this.intSelectedRow = eventData.rowIndex; this.cmMenuItems = new Array<any>(); 

this.cmAddMenuItem(0, "", "item 1"); this.cmAddMenuItem(0, "", "item 2"); this.cmAddMenuItem(0, "", "item 3"); this.cmAddMenuItem(0, "", "Remove"); 

if (this.cmMenuItems.length !== 0) { 

this.contextMenuService.show.next({ 

contextMenu: 

this.cmNew, event: me, item: 

this.oDiagnosisSelected, 

});

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Ah, ok.  That makes more sense.

Remove the `<ul>` and `<li *ngFor...>` from your context menu template and change `#cmNew` to look like this:
```html
Debug: {{ cmMenuItems | json }}
<context-menu #cmNew>
        <template *ngFor="let action of cmMenuItems" contextMenuItem let-item
          [divider]="action.divider" (execute)="onContextMenuItemSelected($event.event, $event.item)">
          {{ action.name }}
        </template>
      </context-menu>
```

And in `onSelectedDiagnosisRowSelect` add the following debug lines:
```ts
console.log(this.cmNew);
console.log(this.cmMenuItems);
```

Let me know what you get.

**Comment by gjenner** [comment]
J Much closer, the menu is displayed, I need to work on action, but that should not be a problem

Now… the menu has no style, just a list of blue hyperlinks, and no dividers (which I added to the cmMenuActions) L

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
The styles aren't provided by the library - that's all up to you.  If you include the bootstrap css file, there are classes on the context menu that should match what bootstrap is expecting.

**Comment by gjenner** [comment]
I have bootstrap css (maybe too old)

Finally (I hope and I am sure you do too), the (execute) does not fire

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
I am not seeing how the actions object I created is being used, thereby, not sure how to add dividers

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Is `onContextMenuItemSelected` available in the context of the `<context-menu #cmNew>`?

For dividers - your actions object is not being used, only the cmMenuItems array.  #cmNew is looking for a divider property on each cmMenuItem.

**Comment by gjenner** [comment]
Yes, I have that… also, the divider is not displaying

 

***************** menu's, outside of the main HTML ***************** 

<context-menu #cmNew>

  <template *ngFor="let action of cmMenuItems" contextMenuItem let-item [divider]="action.divider" (execute)="onContextMenuItemSelected($event.event, $event.item)">

  {{ action.name }}

  </template>

</context-menu>

 

 

***************** populate list  ***************** 

  onSelectedDiagnosisRowSelect($event): void {

     this.boolChronicSelected = true;

    let me: MouseEvent = $event.originalEvent;

 

    let eventData: any = $event;

    // this.objAppointmentSelectedResult = this.objAppointments[eventData.rowIndex];

 

    this.intSelectedRow = eventData.rowIndex;

    this.cmMenuItems = new Array<any>(); this.cmMenuActions = new Array<any>();

  

        this.cmAddMenuItem(0, "", "Secondary");

        this.cmAddMenuItem(0, "", "Primary");

 

    this.cmMenuItems.push({ divider: true, visible: true, });

    this.cmAddMenuItem(0, "", "Edit item");

    this.cmAddMenuItem(0, "", "Delete item (entered in error)");

 

 

    if (this.cmMenuItems.length !== 0) {

      this.contextMenuService.show.next({

        contextMenu: this.cmNew,

        event: me,

        item: this.oChronicSelected,

      });

    };

  };

cmAddMenuItem(intIDENTITY: number, strCode: string, strDescription: string): void {

    let cd: CodeDescription = new CodeDescription;

    cd.IDENTITY = intIDENTITY;

    cd.Code = strCode;

    cd.Description = strDescription

    let cmMenuItem: any = {};

    cmMenuItem = {

      name: cd.Description,

      CodeDescription: cd,

      // html: () => cd.Description,

      // click: () => { this.onContextMenuItemSelected(strDescription, cd); }

    };

    this.cmMenuItems.push(cmMenuItem);

    let cmMenuAction: any = {};

    cmMenuAction = {

      html: (item) => cd.Description,

      visible: (item) => true,

      enabled: (item) => true,

      // html: () => cd.Description,

      // click: () => { this.onContextMenuItemSelected(strDescription, cd); }

    };

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
Sorry, so many little nuances.

First, when I left mouse the table, the cmMenuItems populates, but the contextMenu does not display until the second time I left mouse (then it keeps working correctly).

As I stated, the style is a blue hyperlink, so when I mouse over the contextMenu option, it displays “localhost:4200” (my development address) in the bottom left of the screen

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
I think I should be reverting to the below (the way the website says it should be) and figure out why the styling is missing, which may be why it is not populating the context menu

The action works, there is a space for the divider, it populates on the first click

 

src/app/bootstrap/css/bootstrap.css has a version of v3.3.7

 

<ul>

  <li *ngFor="let item of cmMenuItems" [contextMenu]="cmNew" (click)="onContextMenuItemSelected($event, item)">{{item?.name}}

    <context-menu #cmNew>

      <ng-template *ngFor="let action of item.cmMenuActions" contextMenuItem let-item [visible]="action.visible" [enabled]="action.enabled"

        [divider]="action.divider">

        {{ action.html(item) }}

      </ng-template>

   </context-menu>

  </li>

</ul>

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
So I am guessing you have no idea what the problem is…

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Not without debugging tools.

**Comment by gjenner** [comment]
OK, I see what the problem is.  I misunderstood that my cmMenuItems were the items to populate the comtext-menu

 

So my question now is how do I attach the context-menu to the ag-grid?   

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
Never mind, thanks you

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
Regarding the needing two clicks to display the menu:

Debugging showed it was displaying the previous items.  so wrapping the contextMenuService,show.next with a timer solved this

 

Any help in why the (execute) is failing would be appreciated (again with a mouse over on the context-menu-item, localhost: 4200 is displayed, which suggests to me it is seeing it as a hyperlink)

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
And now that the timer is working, an execute is firing.

It is going to the onSelected function, but firing the localhost:4200 (the hyperlink being displayed)

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
All resolved with the context menu, changed the onSelect.  I do not like that the localhost:4200 is displayed if that can be hidden

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
I'm glad you figured it out.  Please file a separate issue about the link destination saying "localhost:4200".

**Comment by gjenner** [comment]
Thank you, I noticed your demo does the same thing…

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com
