### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by kuhlschrank** [isaacplmann/ngx-contextmenu#123]
Hi,

are there plans to port to Angular 6 soon?
ngx-contextmenu is the last project in our application's stack that is not ready for Angular 6 now...

Regards,
Florian

**Comment by isaacplmann** [comment]
version 5.0.1 supports angular 6. What issues are you finding?

**Comment by kuhlschrank** [comment]
oh wow... sorry...
It seems I kinda just confused 5.0.1 with "a version for Angular 5"!
My bad.

Please close this issue and keep up the good work!
