### ISSUE TITLE
Context menu doesn't display when invoked via ContextMenuService

### ISSUE THREAD

**Issue by dejancg** [isaacplmann/ngx-contextmenu#126]
Hello,

I seem to be having a problem similar to what was described here: https://github.com/isaacplmann/ngx-contextmenu/issues/93

I have this in the component template code:

```
<div class="content">
  <table>
    ...
  </table>
</div>
<context-menu #menu>
    <ng-template contextMenuItem let-item (execute)="console.log($event)">
        Menu item label
    </ng-template>
</context-menu>
```

I have this in the component typescript code:

```
...
import { ContextMenuService, ContextMenuComponent } from 'ngx-contextmenu';

@Component({
    ...
})

constructor(
       ...,
      private contextMenuService: ContextMenuService
    ) {
   ...
   }

@ViewChild('menu') public menu: ContextMenuComponent;

onContextMenu(event: any) {
        if (event.target.tagName.toLowerCase() !== 'td') {
          return;
        }

        const rowIndex: number = event.target.parentElement.dataset.itemIndex - this.state.skip;
        const rowData = this.dataSource[rowIndex];
        console.log(this.menu);
        this.contextMenuService.show.next({
            contextMenu: this.menu,
            event: event,
            item: rowData,
        });
        return false;
    }
```

The `onContextMenu` event is successfully caught and `console.log(this.menu);` line displays the ContextMenuComponent instance in the console.

I have imported the module into app.module.ts using `ContextMenuModule.forRoot()`.

There are no errors in the console. Am I missing something?

**Comment by dejancg** [comment]
The problem was solved by adding `[contextMenu]="menu"` to the above table in the component template.

**Comment by a30001735** [comment]
Hi can you please share the whole solution. I am trying use from a different component and keep getting the error Cannot read property 'disabled' of undefined. Error is being pointed to this section of the code in ngx-contextmenu.js.
`    function (event) {
        if (!this.contextMenu.disabled) {`
