### ISSUE TITLE
Can each submenu has its own item dynamically attached to parent menu item?

### ISSUE THREAD

**Issue by Airex** [isaacplmann/ngx-contextmenu#127]
Can each submenu has its own item dynamically attached to parent menu item?

> Item1
    > Remove 
    > Rename
> Item2
   > Remove
   > Rename

**Comment by isaacplmann** [comment]
I'm not sure exactly what you're asking for

**Comment by Airex** [comment]
I want sub menus operate with different item in same context menu

**Comment by Airex** [comment]
I have ended with dynamic generation of submenus

 <ng-template *ngFor="let action of contextMenuActions" contextMenuItem let-item [visible]="true" [enabled]="true" (execute)="action.handler()" [subMenu]="action && action.filter?filterMenu:(action && action.isDowntime?findDownTimeMenu(action):null)">
        <img [src]="action.icon" alt="{{action.text}}" *ngIf="!!action.icon" class="menu-icon">{{action.text}}
    </ng-template>

referencing them with ViewChildren 
` @ViewChildren(ContextMenuComponent) downtimeMenus: QueryList<ContextMenuComponent>;`

and then I search for related one in [subMenu]

`  <ng-template *ngFor="let action of contextMenuActions" contextMenuItem let-item [visible]="true" [enabled]="true" (execute)="action.handler()" [subMenu]="action && action.filter?filterMenu:(action && action.isDowntime?findDownTimeMenu(action):null)">
        <img [src]="action.icon" alt="{{action.text}}" *ngIf="!!action.icon" class="menu-icon">{{action.text}}
    </ng-template>`

` findDownTimeMenu(action: any) {
        return this.downtimeMenus.find(it => it.menuClass.indexOf(action.item.id) >= 0);
    }`


So. I want like this but without ugly hacks

**Comment by isaacplmann** [comment]
I understand what you're trying to do now, and I can't think of a clean way to do it.  The main issue is that the (execute) event doesn't tell you the whole path the menuItem that you selected.

I think you're hack is the only way to do it right now.  I'd be open to a PR that passes additional information to the execute function.

**Comment by Airex** [comment]
Path is not really important, it could be easier here to be able to do something like this
`<ng-template *ngFor="let action of contextMenuActions" contextMenuItem [contextMenuSubject]="action.data`

and pass this data to submenu item property when open it.
