### ISSUE TITLE
Appending contextmenu to an element 

### ISSUE THREAD

**Issue by Jamlearner** [isaacplmann/ngx-contextmenu#128]
version: `ngx-contextmenu": "^2.0.0-beta.7`
angular: `4.4.6`

Hi @isaacplmann,

I am attempting to try appending contextmenu with (click) event to another element when clicked.

In template, I have a DIV which I attempt to append the contextmenu
`<h2 (click)="onContextMenu($event, 'item')">click to append</h2>`
`<div #appendDiv style="background:black;width:100px;height:100px"></div>`

In code, I have
```
    @ViewChild('appendDiv') public appendDiv: ElementRef;
    public onContextMenu($event: any, item: any): void {
        console.log('appendDiv', this.appendDiv);
        console.log('$event', $event);
        this.contextMenuService.show.next({
            anchorElement: this.appendDiv.nativeElement.target,
            event: <any>$event,
            item: '',
        });
        $event.preventDefault();
        $event.stopPropagation();
    }
```

I was expecting after clicked on `H2`, the contextmenu will be appended on the `DIV`. Did i misuse `anchorElement`? is anything missing on my part?

**Comment by isaacplmann** [comment]
Try this:
`anchorElement: this.appendDiv.nativeElement`

**Comment by isaacplmann** [comment]
I know this works in the latest version of `ngx-contextmenu` - I haven't looked at that older version in a while.

**Comment by Jamlearner** [comment]
Just to confirm, 2.0.0-beta.7 is the latest version for Angular 4 support?

**Comment by isaacplmann** [comment]
Yes, that's correct.

**Comment by isaacplmann** [comment]
Looking at the changelog, `anchorElement` was added in 4.1.x.

**Comment by Jamlearner** [comment]
Thanks, but I remember seeing anchorElement supported in 2.beta but only support on `Element` but not `ElementRef`.
