### ISSUE TITLE
Long Div, right click stops working after top of div reaches top of window view

### ISSUE THREAD

**Issue by LeoTanoue** [isaacplmann/ngx-contextmenu#138]
Hi, I'm having an issue where a have a long div using the context menu and it works great for the most part BUT if I scroll down to the point where the top of the div goes over the top of my window view the right click stops working (there's no error on the console). I'm on Angular 5.2.9 and ngx-contextmenu 4.2.0. Has this issue been fixed on newer versions or am I doing something wrong?

Thank you,
Leo

**Comment by isaacplmann** [comment]
I didn't explicit fix any issue like that.  It might have been fixed in the underlying `@angular/cdk` library that went from 5.x to 6.x.

Do you have some custom position code for your context menu?  It would help to see more of what you're doing.

**Comment by LeoTanoue** [comment]
I've been trying to duplicate the issue on a simple project but I can't, it must be something specific to the code on my project.

**Comment by LeoTanoue** [comment]
I eventually found out I had some CSS blocking things. After cleaning the code everything is working fine.
