### ISSUE TITLE
Angular 7 Update

### ISSUE THREAD

**Issue by SergejSa** [isaacplmann/ngx-contextmenu#144]
Hello,

will be an update on the angular CDK dependency?
Im getting an warning on material update.

"Package "ngx-contextmenu" has an incompatible peer dependency to " @angular/cdk" (requires "^6.0.0, would install "7.0.0").

not sure if it works if i force  the update anyway.

**Comment by isaacplmann** [comment]
Fixed in 5.1.0.  I just needed to update the peer dependencies.  No code change was needed.

**Comment by isaacplmann** [comment]
Oops.  Typo in the peer dependency. 5.1.1 coming soon

**Comment by isaacplmann** [comment]
Ok, try in 5.1.1

**Comment by SergejSa** [comment]
thx it works.
