### ISSUE TITLE
Problem loading the module with Angular Seed

### ISSUE THREAD

**Issue by Adsime** [isaacplmann/ngx-contextmenu#15]
My project seems to struggle with loading the contextmenu module. When I launch the app, I get this console error:

`(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/traceur.js
      Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/traceur.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange]
(http://localhost:5555/node_modules/zone.js/dist/zone.js?1492524996291:1199:29) [<root>]
	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1492524996291:165:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1492524996291:460:38) [<root>]
	Error loading http://localhost:5555/node_modules/traceur.js
	Unable to load transpiler to transpile http://localhost:5555/node_modules/ngx-contextmenu/lib/index.js
	Error loading http://localhost:5555/node_modules/ngx-contextmenu/lib/index.js as "ngx-contextmenu" from http://localhost:5555/app/app.module.js`

I want to highlight the last bit `Error loading http://localhost:5555/node_modules/ngx-contextmenu/lib/index.js as "ngx-contextmenu" from http://localhost:5555/app/app.module.js` as it seems that the module is not being loaded. Am I supposed to use some other name than ngx-contextmenu as the module name? 

From the sources tool in Chrome, I can confirm that it's not being loaded. It is however in my project. Any input for what might be wrong here?

**Comment by isaacplmann** [comment]
I'm not packaging it correctly for SystemJS.  See #5.  I'll close this issue since I'm tracking it in the other issue.  I'll try to work on it by the end of the week.  PRs welcome!

**Comment by teterovic** [comment]
any progress on this ?

**Comment by isaacplmann** [comment]
Nope, but when there is issue #5 is where I'll post about it.
