### ISSUE TITLE
Why Angular Material dependencies require if I want to use Bootstrap?

### ISSUE THREAD

**Issue by patrickrioux** [isaacplmann/ngx-contextmenu#154]
If I want to use with Bootstrap why I need to include Angular Material dependencies?

Is there a way to use that component without @angular/cdk?

**Comment by isaacplmann** [comment]
@Angular/cdk has no styling. It's there to provide base level
functionality. You can apply bootstrap or any styling you want on top

**Comment by patrickrioux** [comment]
Thank you for the quick response.
