### ISSUE TITLE
Providing the context menu on mouseover instead of right mouse click

### ISSUE THREAD

**Issue by KwintenP** [isaacplmann/ngx-contextmenu#16]
Hi, 

Thanks for OS this cool utility. I integrated it and it works quite nicely. 

On the project I integrated this in, they would love to have a way of making the context menu show on any mouseover event. As I saw in the source code, this is currently not supported. Do you think this could be added as an option or do you have a practical reason not to add this?

If you want to, I could provide a PR with the necessary changes to do so.

Kind regards

**Comment by isaacplmann** [comment]
You should be able to do it without a PR.  See [here](https://github.com/isaacplmann/ngx-contextmenu#triggering-the-context-menu-with-a-different-event).  Just use (mouseover) to trigger the context menu.

**Comment by KwintenP** [comment]
My bad! Thanks for the swift response!
