### ISSUE TITLE
Angular 8 Ivy support

### ISSUE THREAD

**Issue by ArtinRezaee** [isaacplmann/ngx-contextmenu#161]
Context menu breaks with Angular 8 and the new Ivy engine. 
![image](https://user-images.githubusercontent.com/22065489/58983474-1e040400-8794-11e9-8dcd-b5ba3b9fc0f0.png)

**Comment by 7185** [comment]
I think I made it work in my project by manually removing all Renderer occurrences but it would be nice to have Ivy support by default.

**Comment by isaacplmann** [comment]
Fixed in version 5.3.0
