### ISSUE TITLE
Click on Menu item reload the page

### ISSUE THREAD

**Issue by henkensm** [isaacplmann/ngx-contextmenu#17]
Hi,

When I Click on the menu item istead of doing the action the page reload.

Did I miss something or is it an issue.

Thank you.

**Comment by henkensm** [comment]
I found why,

When the execute event handler throw and error the preventdefault adn stop propagation are not called. It could be a nice to called first the preventDefault and stoppropagation.

KR

Michaël

**Comment by isaacplmann** [comment]
Thanks for reporting and diagnosing this.  I'd noticed it a few times, but wasn't sure how to fix it.

Should be fixed in 1.0.4.  There will be an error in the console, but the page won't reload.

**Comment by isaacplmann** [comment]
Assuming this works for you. Closing.
