### ISSUE TITLE
IVY v9.0.0-next.11 fail

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [isaacplmann/ngx-contextmenu#177]
yeah, it's because of the old Renderer removal, seems the library here is still using that.
Time to upgrade to Renderer2 I would say ;)
![image](https://user-images.githubusercontent.com/1098243/66915574-9b306700-f019-11e9-94df-d56d77f75214.png)

**Comment by isaacplmann** [comment]
Fixed in version 5.3.0
