### ISSUE TITLE
Error in transpiled JavaScript

### ISSUE THREAD

**Issue by jcorekin-ASRC** [isaacplmann/ngx-contextmenu#188]
**Describe the bug**
I'm having difficulty using this component under Angular 8.  Instead of producing the intended menu, I just get stack trace and the standard menu.  I realized that I might be doing things incorrectly, but I'm not sure how, if this is not a bug, any guidance to solve my issue would be very appreciated.

**To Reproduce**
Click where you would expect to produce the menu.  Instead of seeing the expected alternative context menu, you will see the standard browser context menu.  If you then look at the console screen you will see this error and stack trace in the console:

> GraphComponent.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'disabled' of undefined
>     at ContextMenuAttachDirective.onContextMenu (ngx-contextmenu.js:1099)
>     at Object.eval [as handleEvent] (GraphComponent.html:3)
>     at handleEvent (core.js:43993)
>     at callWithDebugContext (core.js:45632)
>     at Object.debugHandleEvent [as handleEvent] (core.js:45247)
>     at dispatchEvent (core.js:29804)
>     at core.js:42925
>     at HTMLLIElement.<anonymous> (platform-browser.js:2668)
>     at ZoneDelegate.invokeTask (zone-evergreen.js:400)
>     at Object.onInvokeTask (core.js:39680)

I took a look at `ngx-contextmenu.js:1099` and the code that is there appears reasonable, I cannot find it's TypeScript conterpart anywhere.

**Expected behavior**
I would expect the context menu to show up and the standard menu not to.

**Comment by isaacplmann** [comment]
Does this solution help you?

https://github.com/isaacplmann/ngx-contextmenu/issues/150

**Comment by jcorekin-ASRC** [comment]
I'm sorry for the slow response.  Yes it does help.  That said, I'm actually looking over the internals of your component now as I am trying to make use of it in conjunction with Plotly JS.  If there is interest and I receive proper permission, I might offer to push my changes upstream.  Once again, thanks for the help.
