### ISSUE TITLE
examples in Readme have errors.

### ISSUE THREAD

**Issue by malinich** [isaacplmann/ngx-contextmenu#19]
examples have syntax errors. If they exists it mean you no have run them and i cant trust to them.

**Comment by petercmuc** [comment]
Here some errors that I have found in ['Dynamic context menu'](
https://github.com/isaacplmann/ngx-contextmenu#dynamic-context-menu)
'<**template**...' should be '<**ng-template**..'
'{{ action.html(**item**) }}' should be '{{ action.html(**$event.item**) }}'

**Comment by isaacplmann** [comment]
Updated.  Thanks!
