### ISSUE TITLE
separator/divider

### ISSUE THREAD

**Issue by isaacplmann** [isaacplmann/ngx-contextmenu#2]
_From @gjenner on March 21, 2017 15:23_

is it possible to add a divider (or separator) in code rather than HTML?

_Copied from original issue: isaacplmann/angular2-contextmenu#58_

**Comment by isaacplmann** [comment]
[Kind of](https://github.com/isaacplmann/angular2-contextmenu/issues/15#issuecomment-252943752), I updated the linked comment to show how to use a dynamic data in code to update the html template.  I think that html should stay in templates.

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 14:24_

Thank you, I have been able to populate in code-behind, but the example of divider does not seem to work.  It allocates the space, but does not show the divider, and is selectable.

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
I guess I’ll have to actually test my code sample before sharing it.  I’ll having a working example for you soon.

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 14:38_

Thank you so much

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
I just updated the demo code in the repo to create a divider like in the linked comment.  It's working in the demo.  What version of bootstrap are you using?  Can you show me what the rendered html looks like when the divider doesn't show correctly?  Did you add `[divider]="action.divider"` to the `contextMenuItem`?

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 14:51_

OK, a couple of challenges

1.       My HTML is just <context-menu></context-menu>, as I push everything in code-behind (I am old school that way)

2.       When I do add an empty <template [divider]=”action.divider”></template>, I get ‘divider’ is not a known property of ‘template’

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
You need to add the `contextMenuItem` directive to the template element.

```html
<template contextMenuItem [divider]=”action.divider”></template>
```

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 14:58_

Thank you for your patience.  Cannot read property ‘divider’ pf undefined

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
That means that `action` is undefined.  You could statically set `[divider]="true"` or use all the example code:

``` html
<ul>
    <li *ngFor="item in items" [contextMenu]="contextMenu" [contextMenuSubject]="item">Right Click: {{item.name}}</li>
</ul>
<context-menu>
  <template *ngFor="let action of contextMenuActions" contextMenuItem let-item
    [visible]="action.visible" [enabled]="action.enabled" [divider]="action.divider"
    (execute)="action.execute($event.item)">
    {{ action.html(item) }}
  </template>
</context-menu>
```

``` js
@Component({
  ...
})
export class MyContextMenuClass {
  public items = [
      { name: 'John', otherProperty: 'Foo' },
      { name: 'Joe', otherProperty: 'Bar' }
  };
  @ViewChild(ContextMenuComponent) public contextMenu: ContextMenuComponent;
  public contextMenuActions = [
        {
          html: (item) => `Say hi!`,
          click: (item) => alert('Hi, ' + item.name)
          enabled: (item) => true,
          visible: (item) => item.type === 'type1',
        },
        {
          divider: true,
          visible: true,
        },
        {
          html: (item) => `Something else`,
          click: (item) => alert('Or not...'),
          enabled: (item) => false,
          visible: (item) => item.type === 'type1',
        },
      ];
}
```

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 15:15_

Just so close.  I just find all of the data logic in HTML difficult to debug.  I added the [divider]=”true”, [visible]=”true” [enabled]=”true”

My items are now not visible

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Can you post your entire html snippet?

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 15:30_

Made item [visible]=>true, fixed that, but still no visible divider and it is selectable, sorry

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Don't apologize, you're helping me make the library more robust.  But I do need more of your code to help diagnose the problem.

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 15:50_

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Your html template should create a `contextMenuItem` for each item in the `cmMenuItems` array using `*ngFor`.  Like this:

```html
<context-menu #cmNew>
  <template *ngFor="let action of cmMenuItems" contextMenuItem let-item
    [visible]="action.visible" [enabled]="action.enabled" [divider]="action.divider"
    (execute)="action.execute($event.item)">
    {{ action.html(item) }}
  </template>
</context-menu>
```

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 16:20_

This was working great, except the divider, now back to “cannot read property ‘divider’ of undefined

And since it is in HTML, cannot debug easily.  Not a fan of HTML, my last program was Silverlight, loved it

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Do a console.log of your cmMenuItems and check if there’s an item in the array that is null.

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 16:30_

Each object is

click: ()

divider: ()

enabled: ()

html: ()

visible: ()

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 16:39_

Missed part of my previous code behind

if (this.cmMenuItems.length !== 0) {

      this.contextMenuService.show.next({

        // Optional - if unspecified, all context menu components will open

        contextMenu: this.cmNew,

        actions: this.cmMenuItems,

        event: me,

        item: this.objAppointmentSelectedResult,

 

      });

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 16:39_

This all worked well, except for the divider

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Just remove the `actions` property of the `this.contextMenuService.show` call.  You’re already specifying the actions in the html template.

this.contextMenuService.show.next({
// Optional - if unspecified, all context menu components will open
contextMenu: this.cmNew,
event: me,
item: this.objAppointmentSelectedResult,
});

**Comment by isaacplmann** [comment]
_From @gjenner on March 24, 2017 17:45_

It would not even display when I did that

I do appreciate your valuable time, but I am going to revert to where I was this morning and revisit it another day, but again, thank you

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Ok.  You’re welcome. Let me know if you want to give it a try again.

**Comment by isaacplmann** [comment]
_From @symbyte on March 27, 2017 0:28_

I feel like I'm experiencing something similar. Using I'm trying to use the following markup to place a divider in an already existing and functioning context menu: 

```
    <template contextMenuItem divider="true"> </template>
```

At first, I was trying to use the attribute binding syntax (`[divider]="true"`), but was being given the angular template compiler error that `divider` isn't a known property of `template`. I then removed the brackets and am getting an empty, unstyled, anchor tag placed in the menu. 

The rendered output of the divider:
```
<li>
  <a href="">
    <!--template bindings={}--> 
   </a>
</li>
```

and it looks like: 
<img width="202" alt="screen shot 2017-03-26 at 7 27 12 pm" src="https://cloud.githubusercontent.com/assets/6208773/24336786/5b9cc83a-125a-11e7-9dee-2e1f2ac822cb.png">

Any Idea whats going on here?

**Comment by isaacplmann** [comment]
@symbyte using `divider="true"` will set the `divider` property to the string `"true"`.  Using `[divider]="true"` is correct.  You'll get that template compiler error if you forget to include the `contextMenuItem` directive on the `<template>` element.

It should look like this:
```html
<template contextMenuItem [divider]="true"></template>
```

Does that work?

**Comment by isaacplmann** [comment]
_From @symbyte on March 28, 2017 13:9_

As noted above, I did include the `contextMenuItem` directive on the template element. Here's the error message that angular produces: 
```
zone.js:420 Unhandled Promise rejection: Template parse errors:
Can't bind to 'divider' since it isn't a known property of 'template'. ("
    </template>

    <template contextMenuItem [ERROR ->][divider]="true"></template>

    <template
```

I have, as far as I know, imported the module correctly because everything else works as expected. 

Here is my full context menu section of the template for reference: 
```

  <context-menu #contextMenu>
    <template
        contextMenuItem
        let-item
        (execute)="moveToTop($event)"
      >
      Send {{item?.label}} To Top
    </template>

    <template
        contextMenuItem
        let-item
        (execute)="moveToBottom($event)"
      >
      Send {{item?.label}} To Bottom

    </template>

    <template contextMenuItem [divider]="true"></template>

    <template
        contextMenuItem
        (execute)="showAll($event)"
      >
      Show All
    </template>

    <template
        contextMenuItem
        (execute)="hideAll($event)"
      >
      Hide All
    </template>

  </context-menu>
```

**Comment by isaacplmann** [comment]
Can you double check that you’re using a version of angular2-contextmenu that is greater than 0.6.0?  Sometimes the node_modules folder is out of sync with the package.json and you have to either delete and reinstall or manually check the node_modules/angular2-contextmenu/package.json to see what version number it says.

Your code looks just like the demo code in the repo, so it should work...

**Comment by isaacplmann** [comment]
_From @symbyte on March 29, 2017 17:56_

Ah yes. We have the library version locked to 0.5.3 because we were getting some strange behavior with where the menu would appear relative to the location of the click. 

It seems that the same behavior is still present in the most recent release, so I'll open an issue on it in the next few days.

**Comment by isaacplmann** [comment]
@symbyte The positioning problems should be fixed with the move to 1.x.  Let me know if it works for you.

**Comment by isaacplmann** [comment]
Closing.

**Comment by gjenner** [comment]
It appears your Demo at github is not working, just an FYI

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by gjenner** [comment]
Greetings, hoping all is well

So I am upgrading to angular 4, upgraded to ngx-contextmenu

 

If I use your example with the <ng-template… the menu appears correctly.  If I use the <li *ngFor…, the list appears somewhere else on the page.  Do you feel I am doing something obviously wrong?

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
I'll need more information to diagnose your issue.  Can you show me more of your template?

**Comment by gjenner** [comment]
<div >

  <ul >

    

    <li *ngFor="let item of cmMenuItems" [contextMenu]="cmNew" (click)="onContextMenuItemSelected($event, item)">{{item?.name}}</li>

  </ul>

  <context-menu #cmNew>

    <ng-template contextMenuItem (execute)="showMessage('Hi, ' + $event.item.name)">

      Say hi!

    </ng-template>

  </context-menu>

</div>

 

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
Where does the context menu appear in the DOM (Elements tab in Chrome Dev tools) when it's open?  It should be attached to the root app node.

**Comment by gjenner** [comment]
OK, in my code I have the HTML menu with the code behind <ul>, so both appear on the screen, but show up in different locations, see attached

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com

**Comment by isaacplmann** [comment]
I don't think email attachments make it through to the github issue.  You'll either need to paste in the code or drag and drop the files into your reply from the github web ui.

**Comment by gjenner** [comment]
uploaded

 

Thank you in advance,

 

Geordie Jenner

Net Connect Healthcare Systems

www.ncpractice.com
