### ISSUE TITLE
Not compatible with Angular 10

### ISSUE THREAD

**Issue by ElonH** [isaacplmann/ngx-contextmenu#207]
I try to migrate from angular 9 to  10.

```bash
ng update @angular/cli @angular/core @angular/cdk        
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 65 dependencies.
Fetching dependency metadata from registry...
                  Package "ngx-contextmenu" has an incompatible peer dependency to "@angular/cdk" (requires ">=6.0.0 <10.0.0", would install "10.0.1").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

**Comment by hoeni** [comment]
> Is supporting Angular 10 as simple as updating the package.json like in [7b0989f](https://github.com/isaacplmann/ngx-contextmenu/commit/7b0989f739ed93ea0c847d52344ff261685f9872)?

Without reviewing all details I can say I ported my Angular 7 app using ngx-contextmenu to Angular 10 without any problem (except the peer dependency warning).

**Comment by patrickrioux** [comment]
Can the dependencies be updated to match latest Angular 10?

Just to prevent those warnings during build. Thanks.

npm WARN ngx-contextmenu@5.4.0 requires a peer of @angular/cdk@>=6.0.0 <10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-contextmenu@5.4.0 requires a peer of @angular/common@>=6.0.0 <10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-contextmenu@5.4.0 requires a peer of @angular/core@>=6.0.0 <10.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by nithinshiriya** [comment]
When we are going to expect an Angular 10 compatible release.  I am holding an upgrade because of this. Or is there any quick solution?

**Comment by nbaua** [comment]
[ng] Build at: 2020-12-26T04:17:36.338Z - Hash: de4fc44e6c64c41d0772 - Time: 646ms
[ng] Error: The target entry-point "ngx-contextmenu" has missing dependencies:
[ng]  - @angular/cdk/overlay
[ng]  - @angular/cdk/portal
[ng]  - @angular/cdk/a11y

These are not automatically resolved. Making it difficult to bundle in docker-based environment.
We have added this manually for now, however for Angular 10 there must be a quick solution released soon.

**Comment by LucasPaganini** [comment]
A PR has been merged #214 but the new version hasn't been published on NPM yet. @isaacplmann can you publish this please?

**Comment by RickZee** [comment]
Hi @isaacplmann 

When do you think you'll be able to publish to NPM? We're using it on our project and can't upgrade from Angular 9.

Thanks for the component BTW!

**Comment by Ronnysi** [comment]
+1 for the Angular 10 support.
@isaacplmann  - Do you have an eta for the release?

Thanks a lot!!

**Comment by isaacplmann** [comment]
Angular 12 support in 6.0.0

**Comment by nbaua** [comment]
Thats great,
