### ISSUE TITLE
Unable to install ngx-contextmenu for Angular 2 (UNMET PEER DEPENDENCIES)

### ISSUE THREAD

**Issue by LeMalandrin** [isaacplmann/ngx-contextmenu#21]
Hello, I tried to install ngx-contextmenu for my angular 2 app but when I type "npm install --save ngx-contextmenu" on prompt command, i get : 

`+--UNMET PEER DEPENDENCY @angular/common@2.4.10
+-- UNMET PEER DEPENDENCY @angular/core@2.4.10
+-- UNMET PEER DEPENDENCY bootstrap@~3.3.x
-- ngx-contextmenu@1.0.4

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ng2-bs3-modal@0.10.4 requires a peer of bootstrap@~3.3.x but none was installed.
npm WARN ngx-contextmenu@1.0.4 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN ngx-contextmenu@1.0.4 requires a peer of @angular/core@^4.0.0 but none was `installed.`

Is there any way to fix it ?

Thanks

**Comment by isaacplmann** [comment]
npm WARN doesn't actually stop you from compiling.  Do you get any errors when you try to compile and run your app?

**Comment by LeMalandrin** [comment]
So I get : 

> ERROR in C:/Users/Coucke/Documents/angular2/chatty/node_modules/ngx-contextmenu/lib/contextMenu.component.d.ts (1,27): Cannot find module '@angular/core/core'.)

Thank you for your reply :)

**Comment by isaacplmann** [comment]
Try version 1.1.0.  That should be fixed.

**Comment by LeMalandrin** [comment]
So I juste try to install with 
`npm install --save  ngx-contextmenu@1.1.0`

Now it compiles, but I get an error on javascript console : 

`Unhandled Promise rejection: Template parse errors: 'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("nt.preventDefault(); $event.stopPropagation(); menuItem.triggerExecute(item, $event);">
            [ERROR ->]<ng-template [ngTemplateOutlet]="menuItem.template" [ngOutletContext]="{ $implicit: item }"></ng-temp"): ContextMenuContentComponent@8:12
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("rap4"
                [class.disabled]="useBootstrap4 && !isMenuItemEnabled(menuItem)">
            [ERROR ->]<ng-template [ngTemplateOutlet]="menuItem.template" [ngOutletContext]="{ $implicit: item }"></ng-temp"): ContextMenuContentComponent@14:12 ; Zone: <root> ; Task: Promise.then ; Value: `

**Comment by sebsastianek** [comment]
Hi @LeMalandrin , ng-template has been introduced in angular 4.0.0 and this is the version to go with the plugin

for angular 2 You can try https://github.com/isaacplmann/angular2-contextmenu i guess

**Comment by isaacplmann** [comment]
@sebsastianek Thanks for pitching in.  @LeMalandrin yes, you need to upgrade to Angular 4.x to use `ngx-contextmenu` - For angular 2.x you can use `angular2-contextmenu`.
