### ISSUE TITLE
passive-like menu item that emits execute() wanted :)

### ISSUE THREAD

**Issue by andrew-potachits** [isaacplmann/ngx-contextmenu#22]
hi @isaacplmann 

Is it possible to have a menu items that run the execute() method but do not close the menu?

Does it make sense to add new item type or execute() signature can be extended (to return boolean) to control whether item click behavour?

**Comment by andrew-potachits** [comment]
Basically I'm looking for context menu with items that work like a checkboxes. Clicking one item toggles the checkbox but not closes the whole menu.

**Comment by isaacplmann** [comment]
I think you could get close to the functionality that you want using the `passive="true"` option and putting a checkbox or whatever other component you want inside the template.  You could listen to the click event on your component and trigger whatever functionality you want.

i.e.
```html
<ng-template contextMenuItem passive="true">
  <div (click)="doSomething()"></div>
</ng-template>
```

**Comment by andrew-potachits** [comment]
yeah, this just came to my mind as well. as long as I can pass any template, I can pass whole checkboxes group as single item.

Thanks, @isaacplmann
