### ISSUE TITLE
Support Angular 11 and 12

### ISSUE THREAD

**Issue by sroucheray** [isaacplmann/ngx-contextmenu#229]
Hi Isaac,

I provided a PR to support [Angular 11](https://github.com/isaacplmann/ngx-contextmenu/pull/228) and, on top of it another one to support [Angular 12](https://github.com/isaacplmann/ngx-contextmenu/pull/230).

Cheers,

Stéphane

**Comment by isaacplmann** [comment]
Angular 12 support in 6.0.0
