### ISSUE TITLE
how do I disable the menu?

### ISSUE THREAD

**Issue by seiyria** [isaacplmann/ngx-contextmenu#28]
I have some items that simply should not have a context menu, but if I disable all of the menu items, *ngIf the template, etc the menu does not go away. I have a bunch of similar items wrapped in a component that can all be interacted with in different ways, and some cannot be interacted with.

Is there a way to do this?

**Comment by isaacplmann** [comment]
There are two ways I can think of to do this:
1. Use the `[visible]` attribute on the `contextMenuItem`s.  This will still block the browser context menu even when the `ngx-contextmenu` isn't shown.

```html
<ng-template let-item contextMenuItem [visible]="isActionVisible" (execute)="executeSomeAction($event.item)">
  Some action
</ng-template>
```
```ts
public isActionVisible(item): boolean {
  return item.canBeInteractedWith;
}
```

2. Use the `contextMenuService.show.next` method ([like this](https://github.com/isaacplmann/ngx-contextmenu#context-menu-in-a-different-component)) and conditionally trigger the context menu.

```ts
  public onContextMenu($event: MouseEvent, item: any): void {
    if (!item.canBeInteractedWith) {
      return;
    }
    this.contextMenuService.show.next({
      // Optional - if unspecified, all context menu components will open
      contextMenu: this.contextMenu,
      event: $event,
      item: item,
    });
    $event.preventDefault();
    $event.stopPropagation();
  }
```

**Comment by seiyria** [comment]
I did try blocking the visibility and that just shows a blank menu, instead of showing nothing. I suppose I can do onContextMenu but I was hoping to not have a bunch of boilerplate to handle this particular case, much rather just hoping there was an attribute like [contextMenuDisabled] that could have taken care of it. However, having a solution is better than not having one!

Thank you.

**Comment by seiyria** [comment]
This solution doesn't seem to work in my case either. Here is a gif: http://i.imgur.com/vSEZ5Sw.gifv

Code: 

```
  public onContextMenu($event: MouseEvent) {
    $event.preventDefault();
    $event.stopPropagation();

    if(!this.hasMenu) {
      return false;
    }

    this.contextMenuService.show.next({
      contextMenu: this.contextMenu,
      event: $event,
      item: {}
    });

    return false;
  }
```

```
  template: `
    
    <div (contextMenu)="onContextMenu($event)">
    
      <div class="item-container" [isDisabled]="!showDesc" triggers="dblclick:mouseleave" [tooltip]="descText">
        <img [src]="imgUrl" [style.object-position]="spriteLocation" />
        <div class="item-background" *ngIf="showBackground"></div>
        <div class="glow-container {{ glowColor }}" *ngIf="showDesc"></div>
        <span class="count" *ngIf="realCount > 0">{{ realCount }}</span>
      </div>
      
    </div>
    
    <context-menu #contextMenu>
      <ng-template *ngFor="let action of menuOptions" contextMenuItem let-item
        [visible]="action.visible()"
        (execute)="action.execute()">
        {{ action.label }}
      </ng-template>
    </context-menu>
  `
})
```

Not sure if I'm doing something wrong here, though?

**Comment by isaacplmann** [comment]
You may be running into issues with `this` not being what you expect it to be.

Test it with this console.log:
```ts
console.log(this);
this.contextMenuService.show.next({
```

And [this](https://github.com/isaacplmann/ngx-contextmenu#binding-this-for-visible-and-enabled-functions) will help you bind this to what you expect.

**Comment by seiyria** [comment]
`this` is what I expected - the component. However, now it works (?) and I'm not quite sure why, but it doesn't freak out anymore so that's good. I'll keep that bit of documentation handy if something goes awry again.

Thanks again. Any chance you'd be interested in reducing it to binding a variable like `[contextMenuVisible]`?

**Comment by isaacplmann** [comment]
I'll add it to the requested feature list.

**Comment by isaacplmann** [comment]
I've committed a change that adds a `[disabled]` input on the `<context-menu>` element.  I'm working on some other changes too and I should have a new version published later today.  I'll let you know when it is published.

**Comment by seiyria** [comment]
Thank you! That would be of great help in keeping my component simple.

**Comment by isaacplmann** [comment]
Just released 1.2.0 with this enhancement.

**Comment by seiyria** [comment]
thanks, that's great. I'll incorporate it and let you know if I have any issues.

**Comment by seiyria** [comment]
works like a charm, FYI. Thanks a ton!

**Comment by subhabrata2017** [comment]
hey I cant able to change the style of the context menu

**Comment by isaacplmann** [comment]
@subhabrata2017 Please open a new issue and let me know what you've tried
