### ISSUE TITLE
How I can disabled the contextmenu event of ngx-contextmenu item?

### ISSUE THREAD

**Issue by WeiChienHsing** [isaacplmann/ngx-contextmenu#29]
When I right click the ngx-contextmenu item,browser default context menu shows up.
How can I disable this ?

**Comment by isaacplmann** [comment]
There's no good way to do this right now.  The closest you can get is something like this:

```html
<context-menu>
  <ng-template contextMenuitem>
    <div (contextmenu)="$event.stopPropagation();$event.preventDefault()">Something</div>
  </ng-template>
</context-menu>
```

This will stop the context menu on the context menu item itself, but not on the padding around it.

**Comment by dodiya88** [comment]
How can I open the context menu on right click  as well as on left click ?
