### ISSUE TITLE
Z-index of context menu

### ISSUE THREAD

**Issue by johaven** [isaacplmann/ngx-contextmenu#31]
Would it be possible to set the z-index in hard with bootstrap 4 ? 
With angular view method the context menu is displayed below the parent elements.
I fixed the css but the z-index should be that of a popover or a tooltip by default no ?

```css
.ngx-contextmenu {
    z-index: $zindex-tooltip;
}
```

**Comment by isaacplmann** [comment]
I try to ship as little css as possible with this library - relying on appropriate classes to have styles set by bootstrap (or allowing people to write their own styles).  How does bootstrap 4 handle the z-index?  A link would be helpful.

Also, setting z-index on `.ngx-contextmenu` doesn't help much.  You probably want `.ngx-contextmenu > .dropdown-menu`.

**Comment by johaven** [comment]
Z-index on ngx-contextmenu or dropdown-menu is working good. It is not the problem.

By default no z-index was setted on the contextmenu component whereas it is a component of type popover or tooltip. 
Popover or tooltip must be on top of others elements, this seems logical.
You apply a style to ngx-contextmenu like this:
<img width="885" alt="capture d ecran 2017-06-28 a 19 14 27" src="https://user-images.githubusercontent.com/5459596/27650735-1f845c5c-5c36-11e7-9fb9-08b75dec889b.png">

Adding z-index on this style should not be a problem and would prevent to apply an extra css on contextmenu.

$zindex-tooltip on BS4 (scss) is just a shortcut.
Example of values:
```css
$zindex-dropdown-backdrop:  990 !default;
$zindex-navbar:             1000 !default;
$zindex-dropdown:           1000 !default;
$zindex-fixed:              1030 !default;
$zindex-sticky:             1030 !default;
$zindex-modal-backdrop:     1040 !default;
$zindex-modal:              1050 !default;
$zindex-popover:            1060 !default;
$zindex-tooltip:            1070 !default;
```

**Comment by johaven** [comment]
?

**Comment by isaacplmann** [comment]
The problem with hard coding a z-index is that I would be overtly integrating with a particular css framework (BS4 in this case) instead of staying as agnostic as possible.  Other frameworks will use different z-index numbers which may not work with the z-index we've chosen.

You already have to add css to make the context menu look reasonable, so adding a little doesn't seem like it's too much to ask.  You'd do something like this:

**css:**
```css
.ngx-contextmenu > .dropdown-menu {
  z-index: 1060;
}
``` 

or

**scss:**
```scss
// import BS4 variables somehow
.ngx-contextmenu > .dropdown-menu {
  z-index: $zindex-popover;
}
```

**Comment by gjenner** [comment]
I am having a similar problem, the ngx-contextmenu is appearing behind my printNG p-dialog box.  i tried the z-index, no-joy
![image](https://user-images.githubusercontent.com/25956637/31943843-04f562c8-b898-11e7-882c-6d0a10de8e75.png)
