### ISSUE TITLE
Few context menus

### ISSUE THREAD

**Issue by Tarwos** [isaacplmann/ngx-contextmenu#32]
Hello, 

Is some possibility to add few context menus? 
I have a case when one menu I should add to the page and another one to "ng-bootstrap" modal dialog. I have tried to implement few context menus, but it doesn't work. 

Thanks!

**Comment by isaacplmann** [comment]
Which part doesn't work?  There are directions on the readme and the demo
shows multiple context menus.

**Comment by Tarwos** [comment]
Context menu (dynamic) in modal dialog template doesn't work. I have one context menu on the page(feature module) and another inside ng-bootstrap modal dialog(share module) which opened from this page. When I try to open dialog's context menu context service open page's context menu. ContextMenuModule.forRoot imports in app.module.

**Comment by isaacplmann** [comment]
Do both the dialog context menu and the page context menu open?  Or just the page context menu?

Are you passing a `contextmenu` option to `contextMenuService.show.next`?  Please paste in all the relevant templates and typescript code, so that I can help diagnose what's happening.

**Comment by Tarwos** [comment]
Do both the dialog context menu and the page context menu open? - No. Or just the page context menu? - Yes.
Here is a part of component's codes [https://ibb.co/bCBwTQ](url) the similar has ng-bootstrap modal dialog, which is opened from component. And when I triggering contextMenuService.show from dialog, this event works with component's contextmenu, but not with dialog. 

It will be great if you have plunker project with ngx-contextmenu and I can modify related my case, for better understanding.

**Comment by isaacplmann** [comment]
Can you show me the code that triggers the dialog context menu?

You can always clone the repo and modify the demo code to reproduce your issue.

**Comment by Tarwos** [comment]
the similar, in modal component I have:
_...
onModalContextMenu(rowEvent: MouseEvent, rowType: string, rowData: Test): void {   
      this.contextMenuService.show.next({
        contextMenu: this.modalContextMenu, // difference is here only
        event: rowEvent,
        item: rowData,
      });
      rowEvent.preventDefault();
      rowEvent.stopPropagation();
  }_

**Comment by isaacplmann** [comment]
Can you put this line inside `onModalContextMenu`?
```ts
console.log(this.modalContextMenu);
```
Let me know if it is defined.

**Comment by Tarwos** [comment]
Yes, it is defined. Maybe this [screenshot](https://ibb.co/dh3Dsk) will be more helpful

**Comment by isaacplmann** [comment]
Regardless of which `<context-menu>` is opened, I'll still create a `<context-menu-content>` inside the `<app-root>`.  The screenshot doesn't actually show a problem.

Are you able to create a small demo repo that I can take a look at?  Or show me more of your code.  I'm not sure why it isn't working.

**Comment by Tarwos** [comment]
I'm going to prepare small project, don't want to waste your time

**Comment by isaacplmann** [comment]
Not a waste - I want it to work.  Thanks for making a repo.

**Comment by isaacplmann** [comment]
Reopen if you have a repo for this.
