### ISSUE TITLE
Template parse errors: Can't bind to 'contextMenu' since it isn't a known property of 'li'

### ISSUE THREAD

**Issue by yaronmil** [isaacplmann/ngx-contextmenu#33]
getting this error

**Comment by isaacplmann** [comment]
Did you import the module?

**Comment by yaronmil** [comment]
this is my app.module

```
import {ContextMenuModule} from 'ngx-contextmenu';



@NgModule({
  declarations: [
 

  ],
  imports: [
   
    ContextMenuModule.forRoot({
      autoFocus: true,
    }),
  ],
  providers: [ ],
  bootstrap: [ ]
})
export class AppModule { }
```

**Comment by isaacplmann** [comment]
If you're using the `<contextmenu>` in a lazy loaded module, you'll need to import the `ContextMenuModule` in that module as well.  (Or import `ContextMenuModule` into your own `SharedModule` that exports `ContextMenuModule` and then import your `SharedModule` into the lazy loaded module.)

**Comment by yaronmil** [comment]
i replaced the "LI" with "DIV" it is ok now

**Comment by locpt92** [comment]
> If you're using the `<contextmenu>` in a lazy loaded module, you'll need to import the `ContextMenuModule` in that module as well. (Or import `ContextMenuModule` into your own `SharedModule` that exports `ContextMenuModule` and then import your `SharedModule` into the lazy loaded module.)
I follow this comment but it's not working.
