### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by andrewbroderick** [isaacplmann/ngx-contextmenu#34]
Hi,

The menu has no styling (just looks like a regular li bullet point), and sometimes comes up all the way at the left of the screen, instead of at the cursor. I am using Angular 4.0.3 and ngx-contextmenu 1.2.1.

App module:
`import { ContextMenuModule }  from 'ngx-contextmenu';`

Component:
```
import { ContextMenuComponent } from 'ngx-contextmenu';
...
  @ViewChild(ContextMenuComponent) public basicMenu: ContextMenuComponent;
```

HTML:
```
<div style="padding-top: 10px; width: 100%; display: inline-block;"  [contextMenu]="basicMenu">
...

<context-menu>
  <ng-template contextMenuItem>
    Say hi!
  </ng-template>
</context-menu>
```

What am I doing wrong? 
Thanks

**Comment by isaacplmann** [comment]
The library includes classes that work with bootstrap styles, but doesn't provide any actual styling.  You'll need to include bootstrap yourself.

**Comment by andrewbroderick** [comment]
That did it, thanks. One thing I would put in the documentation is the line
`import { ContextMenuComponent } from 'ngx-contextmenu';`
in the component. It's easy to work out, but not immediately obvious.
