### ISSUE TITLE
Can't bind to 'contextMenu' since it isn't a known property of 'li'

### ISSUE THREAD

**Issue by bubbsi** [isaacplmann/ngx-contextmenu#36]
Hello everyone,

I followed the instruction to work with the ngx-contextmenu library. 
After implementing, I only get an error: "Can't bind to 'contextMenu' since it isn't a known property of 'li'".

I don't know what went wrong.
Could you help me plz?

Kind regards,
David.

**Comment by alfonsoara** [comment]
Import ContextMenuModule
 in your @NgModule .. imports.

Alfonso.

**Comment by isaacplmann** [comment]
Thanks @alfonsoara .  Yes, if you don't have `ContextMenuModule` imported, you would get that error message.
