### ISSUE TITLE
Allow closing the menu from a script.  Also problems with spaces in input/passive.

### ISSUE THREAD

**Issue by Thorski** [isaacplmann/ngx-contextmenu#38]
Hi, thank you for the nice context menu.

1.   Is there a way to close the menu via script, for instance on an event.   In particular,
if I have a passive menu with an input text box, in response to a keyup.enter event, I want
to close the menu.

2.  For some reason I cannot type spaces into an input box.

`  <ng-template contextMenuItem passive="true">
    Rename to: <input #rename type="text" (keyup.enter)="onEnter(rename.value)">
  </ng-template>`

The same input box allows spaces elsewhere.

Thank you,

-- Thor

**Comment by isaacplmann** [comment]
1. I should add this to the documentation, but there is a `triggerClose` `Subject` on the `ContextMenuService`.  You can call it with a specific instance of a `ContextMenuContentComponent` to close just that one or with `undefined` to close all open context menus.

```ts
this.contextMenuService.triggerClose.next(undefined);
```

2. That's a bug.  I'm swallowing the `space` key to trigger a context menu item with the keyboard - but that causes problems with your use case.  I'm working on it.

**Comment by Thorski** [comment]
Thank you for the quick response.
The triggerClose works fine.  

-- Thor

**Comment by isaacplmann** [comment]
The 2nd point should be resolved in 1.3.4.  Let me know if it is fixed for you.

Basically, if the `event`'s `target` is an `input` or other editable element, I don't cancel the event.

**Comment by Thorski** [comment]
Works well, thank you.

You are a great man.

-- Thor

**Comment by Thorski** [comment]
The triggerClose Subject on the ContextMenuServicet no longer works.  In the code I find no references to triggerClose other than the definition.  Instead I now use closeAllContextMenus(...).   I am just putting this here in case someone finds this issue and tries to use it.
