### ISSUE TITLE
Dynamic context menu support for html other than simple strings.

### ISSUE THREAD

**Issue by Thorski** [isaacplmann/ngx-contextmenu#40]
I'm trying to make a dynamic context menu with html more complicated than a simple string
but instead the html tags are just shown as raw strings.     See image below.   My real use case
is wanting an input text box.  I also do not seem to be able to set 'passive' in dynamic context menu.

Thanks.

```ts
public contextMenuActions = [
    {
      html: () => `Say hi!`,
      click: () => this.doSomething(),
      enabled: () => true,
      visible: () => true,
    },
    {
      html: () => `Say <b>hi</b>!`,
      click: () => this.doSomething(),
      enabled: () => true,
      visible: () => true,
    },
    {
      html: () => `Rename to: <input #rename type="text" (keyup.enter)="onEnter(rename.value)">`,
      click: () => this.doSomething(),
      enabled: () => true,
      visible: () => true,
      passive: () => true,
    },
  ];
```
![image](https://user-images.githubusercontent.com/28730875/28170551-c6d2d294-67b3-11e7-8de7-8563e527988e.png)

**Comment by isaacplmann** [comment]
You're right `html` should probably be renamed to `text` in that example because it won't do any compiling of html.

To allow something to be passive, you'll need to add that to the `contextMenuItem`: `[passive]="action.passive"`

https://github.com/isaacplmann/ngx-contextmenu#dynamic-context-menu

The structure of `contextMenuActions` is not dictated by `ngx-context-menu` at all, so you could do something like this:

```ts
const contextMenuActions = [
  {
    html: 'Rename to: ',
    showInput: true
  }
];
```

```html
<ng-template *ngFor="let action of contextMenuActions" contextMenuItem let-item
    [visible]="action.visible" [enabled]="action.enabled" [divider]="action.divider"
    [passive]="action.passive" (execute)="action.click($event.item)">
    {{ action.html($event.item) }}
    <input *ngIf="action.showInput" #rename type="text" (keyup.enter)="onEnter(rename.value)">
  </ng-template>
```

**Comment by Thorski** [comment]
Clever.  That worked for me thank you.
-- Thor
