### ISSUE TITLE
How to integrate with D3.js

### ISSUE THREAD

**Issue by GabrielSiq** [isaacplmann/ngx-contextmenu#42]
Hi,

this isn't a problem with the component, but more of a request for help. I'm working on an Angular 4 project with D3.js and I wanted to add context menus when right clicking nodes on a graph. As the d3-contextmenu plugin hasn't been updated to D3V4 or Typescript, I tried adding ngx-contextmenu to my SVG element. Now, I wanted to obtain the nodes right-clicked and trigger a function on them from the context-menu. Any pointers on how to achieve this?

**Comment by isaacplmann** [comment]
I don't think it will work well, since d3 directly manipulates DOM nodes outside of Angular.  You can either (1) use a d3 way of creating context menus by directly manipulating the DOM or (2) use an Angular compatible way of creating charts like `ngx-charts` and then use `ngx-contextmenu` on top of that.

**Comment by GabrielSiq** [comment]
Update: I used `(contextmenu)="onContextMenu($event, null)"` to handle right clicks. Then, I did this:
```
public onContextMenu($event: MouseEvent, item: any): void {
    if ($event.toElement.nodeName === 'circle') {
      this.contextMenuService.show.next({
        // Optional - if unspecified, all context menu components will open
        contextMenu: this.contextMenu,
        event: $event,
        item: item,
      });
      $event.stopPropagation();
    }
    $event.preventDefault();
  }
```

It works as I expected, the click event contains the underlying SVG element with all its attributes and my context menu only triggers when <circle> elements are clicked. Do you see any potential drawbacks to this approach?

Thanks for your help!
