### ISSUE TITLE
Changing start position of context menu

### ISSUE THREAD

**Issue by GabrielSiq** [isaacplmann/ngx-contextmenu#43]
Hello,

I've been playing with ngx-contextmenu and I wanted to ask how can I change where the context menu is created when I right click. Currently I'm applying it to an element that is at the very top of my screen. The context menu's bottom left corner starts at the pointer and grows upwards. As a result, most of it is off the screen for elements at the top. Is there anyway I can easily change this?

Thanks!

**Comment by isaacplmann** [comment]
The context menu tries to orient itself so that it doesn't flow off the side of screen (if possible).  The first orientation it tries is to put the top left corner of the context menu at the mouse location.  Can you give me more details about your app?

1. What does the event object look like?
2. Are you doing any styling using the `position` css property?

**Comment by GabrielSiq** [comment]
Thanks for answering so quickly.

1. Would you like to see an example of generated MouseEvent object?
2. I haven't applied any custom styling to this component or any other yet.

**Comment by isaacplmann** [comment]
1. Yes.

**Comment by GabrielSiq** [comment]
![image](https://user-images.githubusercontent.com/5186043/28927340-ac214032-7840-11e7-847f-4462cca49194.png)
![image](https://user-images.githubusercontent.com/5186043/28927383-c5243418-7840-11e7-95d3-3ac8300d1dfa.png)

**Comment by isaacplmann** [comment]
In your console, enter `document.body.clientWidth` and `document.body.clientHeight` and let me know what they say.

**Comment by GabrielSiq** [comment]
Width returned 1060, Height returned 10

**Comment by isaacplmann** [comment]
The height is the problem.  The context menu thinks it only has 10px of height to work with and is trying to show as much of the context menu as possible in those 10px.  Giving your body a min-height in css will fix the problem, but I'm guessing there is some underlying issue that is stopping your body from knowing its real height.  Are you using float based layout?  Adding a clearfix at the end of the body would help that situation.

**Comment by GabrielSiq** [comment]
clearfix solved it! Thanks!
