### ISSUE TITLE
Use dropup instead of dropdown (for Bootstrap 4)

### ISSUE THREAD

**Issue by pawelchmara** [isaacplmann/ngx-contextmenu#48]
Hi,

it is possible to use bootstrap 4 dropup class instead of dropdown? I need to open context menu above the click coordinates.

Thanks for help

**Comment by isaacplmann** [comment]
It's not as simple as changing a class name - since I'm not using the bootstrap javascript to position the context menu.  That is a good feature to add though.  I'll put it on my todo list.

**Comment by isaacplmann** [comment]
I'm working on a new version using the `@angular/cdk/overlay` that will gracefully handle choosing a different positioning strategy with fallbacks if there isn't enough space in the viewport.

**Comment by pawelchmara** [comment]
Thanks for that information. I will be waiting for this new feature.

**Comment by isaacplmann** [comment]
Try this in version `2.0.0-beta.1`

**Comment by pawelchmara** [comment]
Today I will try this.

**Comment by isaacplmann** [comment]
Actually, try `2.0.0-beta.2`.  beta.1 is broken for angular 4.x apps.

**Comment by pawelchmara** [comment]
I have just reinstalled to version 2.0.0-beta.3 but context menu stop showing (no errors are thrown). Maybe I show you how I use context menu.

In HTML template:

```
<context-menu>
  <ng-template contextMenuItem (execute)="onShowOrderClick($event.item)">
    <div class="d-flex flex-row align-items-center">
      <span class="oi oi-info mr-2"></span> Show
    </div>
  </ng-template>
  <ng-template contextMenuItem (execute)="onEditOrderClick($event.item)">
    <div class="d-flex flex-row align-items-center">
      <span class="oi oi-pencil mr-2"></span> Edit
    </div>
  </ng-template>
</context-menu>
```

In component class:

```
public constructor(
    private qWebChannelService: QWebChannelService,
    private contextMenuService: ContextMenuService
  ) {}
...
@ViewChild(ContextMenuComponent) private contextMenu: ContextMenuComponent;
...
private bindDataTableRowRightClick(row) {
    $(row).contextmenu(($event) => {
      this.onContextMenu($event, $event.currentTarget.id);
    });
  }

private onContextMenu($event: MouseEvent, item: any): void {
    this.clickedRowId = item;

    this.contextMenuService.show.next({
      contextMenu: this.contextMenu,
      event: $event,
      item: item
    });

    $event.preventDefault();
    $event.stopPropagation();
  }
```

**Comment by pawelchmara** [comment]
It's look like a context menu is not initialized (context menu tag is empty):

`<context-menu _ngcontent-c12=""> </context-menu>`

**Comment by isaacplmann** [comment]
Thanks for letting me know.  I'm looking into it.

**Comment by isaacplmann** [comment]
Do you `<!doctype html>` at the top of your `index.html` file?

**Comment by isaacplmann** [comment]
Was the context menu working for you in the 1.x version?

**Comment by pawelchmara** [comment]
Yes, the contex menu was working without any problem. I'm using Angular in version 4.3.5. On the previous question I will give an answer after the weekend.

**Comment by johaven** [comment]
@isaacplmann 
Same problem with 2.0.0-beta.5 and Angular 5.0, context menu stop showing (no errors are thrown). Worked well with Angular 4.x and 1.x builds.

**Comment by johaven** [comment]
https://github.com/isaacplmann/ngx-contextmenu/issues/63 solved my problem
