### ISSUE TITLE
How to get mouseover ng-template?

### ISSUE THREAD

**Issue by bipin244** [isaacplmann/ngx-contextmenu#49]
I want to display help to user before user click on specific context menu link so i want to mouseover event of this menu it's possible?
i want something like that.
![dashboard](https://user-images.githubusercontent.com/13151662/30279903-145c1a82-972c-11e7-865f-b07bede3e06a.png)

**Comment by isaacplmann** [comment]
Absolutely.  You can put any valid angular template logic inside the `contextMenuItem` template.

So something like this would work:

```html
<context-menu>
  <ng-template contextMenuItem (execute)="showMessage('Hi, ' + $event.item.name)">
    <div (mouseenter)="displayMessage()" (mouseleave)="hideMessage()">Say hi!</div>
  </ng-template>
</context-menu>
```

```ts
displayMessage() {
  // display the message somehow
}
hideMessage() {
  // hide the message somehow
}
```
