### ISSUE TITLE
context menu disabling items

### ISSUE THREAD

**Issue by manojsanjeewa** [isaacplmann/ngx-contextmenu#50]
I have tried with enabled property false with context menu item but that does not working.

**Comment by isaacplmann** [comment]
Can you show me some of your code that isn't working?

**Comment by VaniKiran** [comment]
Hi,
 Iam also having issue with disabling a context menuitem.
below is the code iam using

**HTML:**
<ul>
<li [contextMenu]="myContextMenu" [contextMenuSubject]="page"  *ngFor="let page of Pages" >
</ul>
<context-menu #myContextMenu>
    <ng-template contextMenuItem let-item (execute)="test()" [enabled]="isEnabled" >
        Split
    </ng-template>

**Component:**

public isEnabled(item: any): boolean {
        return item > 1;
    }

Help is appreciated.

Thanks

**Comment by VaniKiran** [comment]
Hi,

Got it working. Made below changes to the code which i shared.

public isEnabled(item: any): boolean {
        return item.pageNumber > 1;
    }

 hope this helps if anyone come across the same kind situation.

Thanks

**Comment by isaacplmann** [comment]
I'm glad you got it working.

**Comment by isaacplmann** [comment]
@manojsanjeewa Are you still stuck?

**Comment by manojsanjeewa** [comment]
thanks VaniKiran, isaacplmann. that works for me.
