### ISSUE TITLE
context menu - Chrome vs IE

### ISSUE THREAD

**Issue by gerry2978** [isaacplmann/ngx-contextmenu#51]
Hi - I am trying to use this component in our application. Our primary browser is IE 11. I believe, I have done all the wiring right but context menu is not showing up in my app. However it does show up if I open my app in chrome. Is there anything different I need to do to make it work in IE 11?

Also this link work in chrome but not in IE - https://isaacplmann.github.io/ngx-contextmenu/ 

Can you please advise? Thank you very much

Gerry

**Comment by isaacplmann** [comment]
The demo needed to include some polyfills.  It should be fixed now.  There's nothing else that I know of that is unique to IE 11.  Is the context menu appearing in the DOM?

**Comment by gerry2978** [comment]
Thanks. The link works both in IE and Chrome. No - for IE, the context menu doesn't appear in DOM . For chrome - it does.

**Comment by isaacplmann** [comment]
Can you send me some steps to reproduce?  Or give some information about what you're code looks like?

**Comment by gerry2978** [comment]
I am making sure I have all the pollyfills needed for IE. Which one did you include to make your demo work in IE?

**Comment by isaacplmann** [comment]
In `polyfills.ts`:

```ts
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```

**Comment by gerry2978** [comment]
Thank you very much. Included these polyfills and its working now. Now if I have to open open the context menu on demand (lets say right click on third party grid.), what API I need to use? The grid I am trying to use won't allow usage of [contextMenu]="menuName". Appreciate all the help.

**Comment by isaacplmann** [comment]
[this](https://github.com/isaacplmann/ngx-contextmenu#context-menu-in-a-different-component) is probably what you want.

**Comment by gerry2978** [comment]
Hi - I am trying to make it work on my grid but not successful yet. Question I have is: How do I let service(this.contextMenuService) know which contextMenu to open? In other syntax we do  [contextMenu]="menuName", and component know menuName context menu has to be opened.

<ul>
    <li *ngFor="let item of items" (contextmenu)="onContextMenu($event, item)">Right Click: {{item.name}}</li>
</ul>
import { ContextMenuService } from 'ngx-contextmenu';

@Component({
  ...
})
export class MyContextMenuClass {
  public items = [
      { name: 'John', otherProperty: 'Foo' },
      { name: 'Joe', otherProperty: 'Bar' }
  ];

  // Optional
  @Input() contextMenu: ContextMenuComponent;

  constructor(private contextMenuService: ContextMenuService) {}

  public onContextMenu($event: MouseEvent, item: any): void {
    this.contextMenuService.show.next({
      // Optional - if unspecified, all context menu components will open
      contextMenu: this.contextMenu,
      event: $event,
      item: item,
    });
    $event.preventDefault();
    $event.stopPropagation();
  }
}

**Comment by isaacplmann** [comment]
You specify which context menu by passing the `ContextMenu` component instance to the `ContextMenuService`.

```html
<context-menu #contextMenu>
  ...
</context-menu>
```

```ts
@ViewChild('contextMenu') public contextMenu: ContextMenuComponent;
```

Then pass that contextMenu instance to the `contextMenuService`.
```ts
    this.contextMenuService.show.next({
      // Optional - if unspecified, all context menu components will open
      contextMenu: this.contextMenu,
      event: $event,
      item: item,
    });
```

**Comment by gerry2978** [comment]
That worked. Thank you!
