### ISSUE TITLE
Not compatible with Angular 5.0

### ISSUE THREAD

**Issue by slubowsky** [isaacplmann/ngx-contextmenu#56]
FYI

ERROR in ../node_modules/ngx-contextmenu/lib/contextMenu.options.d.ts(1,10): error TS2305: Module '"C:/.../node_modules/@angular/core/core"' has no exported member 'OpaqueToken
'.

**Comment by isaacplmann** [comment]
Thanks for the heads up.  This would be a great PR for a first time contributer.

**Comment by isaacplmann** [comment]
Fixed in `2.0.0-beta.1`
