### ISSUE TITLE
How to set contextmenu location in DOM

### ISSUE THREAD

**Issue by 7393840** [isaacplmann/ngx-contextmenu#57]
I have a canvas with a contextmenu, like
```
<div>
    <canvas [contextMenu]="contextmenu"></canvas>
    <context-menu>
        <ng-template contextMenuItem>
            ...
        </ng-template>
    </context-menu>
</div>
```
And the canvas need to support full screen. When I let the 'div' element full screen, the contextmenu is under 'app-root', outside the full screen element. How to make the contextmenu under 'div' element?

**Comment by isaacplmann** [comment]
You could specify the root view container as described [here](https://github.com/isaacplmann/ngx-contextmenu/issues/52#issuecomment-331437144).  But what you probably want to do is just set a z-index on the context menu so that it appears above the full screen canvas.  In `styles.scss`:

```css
.ngx-contextmenu > .dropdown-menu {
  z-index: 1060;
}
```

**Comment by isaacplmann** [comment]
The root view container is being replaced by @angular/cdk in version `2.0.0-beta.1`
