### ISSUE TITLE
PR rules

### ISSUE THREAD

**Issue by cwdaniel** [isaacplmann/ngx-contextmenu#58]
I have fixed the issue with #56 , what are the rules for PR's on this repo?

**Comment by isaacplmann** [comment]
I haven't really thought through explicit rules.  Once I start getting too many PRs for me to handle, I'll start putting a process in place.  That's a problem I'd love to have!  If it compiles and the demo runs, go ahead and submit the PR.  If I noticing any issues I'll let you know in the PR itself.

Thanks for jumping in to help!

**Comment by isaacplmann** [comment]
Are you planning to submit your PR?

**Comment by cwdaniel** [comment]
please see PR60

**Comment by isaacplmann** [comment]
Thanks for the PR. Closing this issue.
