### ISSUE TITLE
IContextMenuOptions Warning

### ISSUE THREAD

**Issue by chrism6475** [isaacplmann/ngx-contextmenu#61]
I'm getting several warnings about a missing IContextMenuOptions, but I'm not too sure of why I'm getting it. Is this module necessary, or should I remove the reference in ./contextMenu.options?
![warning](https://user-images.githubusercontent.com/15149443/31735308-1f664432-b407-11e7-900b-f2923fe46155.PNG)

**Comment by isaacplmann** [comment]
Those are warnings that you can safely ignore.  But those are only logged for me when I compile the library itself - not when I consume the library in an app.  How are you importing the library?  Are you doing `import { something } from 'ngx-contextmenu'`?

**Comment by chrism6475** [comment]
Oh okay, good to know!

This is how I'm importing it in my app,module.ts: 
"import { ContextMenuModule } from 'ngx-contextmenu-master/src/lib';"

I used that file path (ngx-contextmenu-master/src/lib) because I get a compile error when I reference 'ngx-contextmenu'. 

Thank you!

**Comment by isaacplmann** [comment]
These warnings will go away in version `2.0.0-beta.1`
