### ISSUE TITLE
invalid build directory of 2.0.0-beta1

### ISSUE THREAD

**Issue by kvetis** [isaacplmann/ngx-contextmenu#62]
Hi, I tried to upgrade to `2.0.0-beta1` but the build is now located in `./lib/src/lib/` instead of `./lib`. I tried to fork your repository and fix it but I couldn't find the problem.

**Comment by isaacplmann** [comment]
Yep `2.0.0-beta.1` was broken.  I released `2.0.0-beta.2` this morning.  Let me know if it works.

**Comment by isaacplmann** [comment]
FYI, the problem was that I build the library with angular 5.x.  That stopped 4.x apps from using it.  Building the lib with 4.x in beta.2 will let 4.x and 5.x apps use it.

**Comment by kvetis** [comment]
I can confirm that the `2.0.0-beta.2` is in correct build folder. I'll report if it works in my `angular-5.0.0-rc5` app later. Thank you, you fixed the build right after I downloaded the `beta.1`.
