### ISSUE TITLE
Angular 5 changes to OpaqueToken 

### ISSUE THREAD

**Issue by antonevane** [isaacplmann/ngx-contextmenu#66]
WARNING` in ./node_modules/ngx-contextmenu/lib/contextMenu.options.js 2:38-49 "export 'OpaqueToken' was not found in '@angular/core'

[See](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced)

**Comment by isaacplmann** [comment]
What version of ngx-contextmenu are you using?  `2.0.0-beta.4` should be compatible with Angular 5.

**Comment by antonevane** [comment]
Sorry for the spam, I was on 1.3.5

**Comment by khanyuriy** [comment]
Not a spam, thanx for question and responce )
