### ISSUE TITLE
(Feature) Hotkeys for context menu option

### ISSUE THREAD

**Issue by celestale** [isaacplmann/ngx-contextmenu#70]
Any thoughts on giving those context menu options a shortcut keys?

**Comment by isaacplmann** [comment]
I'm not sure what you're asking for.  Are you trying to configure which hotkeys interact with the context menu?  Or is there some action that currently doesn't have a hotkey that you want to add?

**Comment by celestale** [comment]
Yes. I would like to config a Keyboard shortcuts to use the context menu. 

Like Ctrl + O to trigger contextMenuItem number 1
Ctrl + K to trigger contextMenuItem number 2
.
.
.

**Comment by isaacplmann** [comment]
You can do that without any changes to the library.  But that does seem like a pretty common requirement, so I should put a section in the docs about it.

Here's what I would do:

```ts
import { HostListener } from '@angular/core';

...

// meta is control on windows and command on mac
@HostListener('window:keydown.meta.o')
executeActionOne() {
  // stuff
}
@HostListener('window:keydown.meta.k')
executeActionTwo() {
  // stuff
}
```
