### ISSUE TITLE
[enabled] no access to current item

### ISSUE THREAD

**Issue by joachim-bl** [isaacplmann/ngx-contextmenu#73]
Hi,
i need to enable a menu item dependend on a property of the item, like so:
     ` <ng-template contextMenuItem let-item (execute)="cm($event)" [enabled]="item?.data.type=='Custom'">
`
but 'item' is always 'undefined', although when I print it out inside the template, i get the correct value.

How can I access item for the enabled property?

regards
Joachim

**Comment by isaacplmann** [comment]
https://github.com/isaacplmann/ngx-contextmenu#context-menu-items

Just make the `[enabled]` property a function instead of a boolean value.

```html
<ng-template contextMenuItem let-item (execute)="cm($event)" [enabled]="isEnabled">
```
```ts
public isEnabled(item: any): boolean {
  return item && item.data.type=='Custom';
}
```
