### ISSUE TITLE
OverlayModule

### ISSUE THREAD

**Issue by FARHANE** [isaacplmann/ngx-contextmenu#74]
I get this error : ERROR in OverlayModule is not an NgModule
When try to add a component that I create using ngx-contextmenu

+ `ngx-contextmenu@2.0.0-beta.7`
+ `@angular/cdk@2.0.0-beta.12`

**Comment by isaacplmann** [comment]
On vacation. I'll check on it on Monday

**Comment by FARHANE** [comment]
Ok thank you,
Just an observation: when I save a file in the projet the compilation is fired and I dont have this error any more.
but when I do ng build I get the error again

**Comment by isaacplmann** [comment]
What version of angular are you using?

**Comment by FARHANE** [comment]
I am using Angular version 4.1.3

**Comment by webcat12345** [comment]
Is there any schedule to support @angular/cdk latest version?

**Comment by isaacplmann** [comment]
I've tested it with 5.0.0-rc.2.  If there's an error with rc.3 please report it in a new issue.  I always try to stay up to date.

**Comment by isaacplmann** [comment]
I'm assuming this is no longer a problem.  Reopen if you're still having this issue.
