### ISSUE TITLE
Sub-menus not intelligently choosing where to display

### ISSUE THREAD

**Issue by JohnArrowwood** [isaacplmann/ngx-contextmenu#75]
If I have a context menu that has a sub-menu, the sub-menu displays positioned relative to the item that triggers it.  However, if that parent menu item is down near the bottom of the screen, the sub-menu can end up off the bottom of the screen.

Child/sub menus should intelligently position themselves vertically as well, to keep them on screen.

![image](https://user-images.githubusercontent.com/7828933/32951602-78090830-cb78-11e7-9614-1f35d9a718cb.png)

**Comment by isaacplmann** [comment]
Thanks for the bug report. I'll take a look on Monday

**Comment by isaacplmann** [comment]
This is fixed in version `3.0.0`.  (The major version bump is because the latest version of `@angular/cdk` drops support for angular 4.x.)
