### ISSUE TITLE
can set component under context-menu

### ISSUE THREAD

**Issue by dyh333** [isaacplmann/ngx-contextmenu#84]
hi, @isaacplmann . if the context menu is complex, can i build it as a component and put it under context-menu?  like below ?

<context-menu #enableAndVisible (close)="showMessage('closed', $event)">
  <ng-template>
   <my-comp></my-comp>
</ng-template>

**Comment by isaacplmann** [comment]
If you're asking about [sub-menus](https://github.com/isaacplmann/ngx-contextmenu#sub-menus), yes you can do that.

FYI, there's currently a bug (#83) that makes the `(close)` output not fire.
