### ISSUE TITLE
ERROR: Attempting to attach an unknown Portal type. BasePortalHost accepts either a ComponentPortal or a TemplatePortal.

### ISSUE THREAD

**Issue by celestale** [isaacplmann/ngx-contextmenu#85]
Hello @isaacplmann,

Version: 2.0.0-beta.7
Angular: 4.x

I have attempts to use your beautiful context menu in my local app with my angular component that is going to be injected into another owned module in npm. This owned module was installed as a package in my local app.

Following the basic setup which is to import ContextMenuModule.forRoot into my local app and tested the basic template code provided. But because this component is going to be injected into my another owned module, i receive some errors that I dont understand to fix.

**Error A**

> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'
> Field 'browser' doesn't contain a valid alias configuration
> Can't bind to 'contextMenu' since it isn't a known property of 'span'.

**template.html (local app)**
```
<span [contextMenu]="basicMenu">{{ myData() }}</span>
<context-menu>
    <ng-template contextMenuItem let-item>Hello</ng-template>
    <ng-template contextMenuItem let-item>Bye</ng-template>
</context-menu>
```

**template.ts (local app)**
```
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    moduleId: module.id,
    templateUrl: './template.html'
})
@ViewChild(ContextMenuComponent) public basicMenu: ContextMenuComponent;
```

**app.module.ts (another owned module that I installed as package in my local app)**
```
@NgModule({
    imports: [
         ContextMenuModule.forRoot({
             autoFocus: true
         })
    ],
...
exports: [
        ContextMenuModule,
    ]
...
```
I tried to fix Error A, I went to the another owned module and import  ContextMenuModule.forRoot() again in that module NgModule imports[]. The application compiles and start with no errors but when I Right-Click on the <span> element, I get this error that I dont understand.

> ERROR: Attempting to attach an unknown Portal type. BasePortalHost accepts either a ComponentPortal or a TemplatePortal.

**Comment by isaacplmann** [comment]
Can you share the dependencies section of your `package.json`?  Specifically, what version of `@angular/cdk` are you using?

**Comment by celestale** [comment]
Thanks for your reply. I have resolved that issue because I misplace the imports. 

Before we close the issue,  just curious, how can I put this directive into a HTML element within typescript file?

I tried 
`this.renderer.setProperty(el, '[contextMenu]', 'basicMenu');`

el points to a (div) element that I do not have the HTML file access. It is an element generated by other packages.

I cannot do the normal way `<div [contextMenu]='basicMenu'> ... </div>` to bind it.

**Comment by isaacplmann** [comment]
I don't know of a way to dynamically add a directive to an element.  You can dynamically create a component with ComponentFactoryResolver, but there's a much easier way to accomplish what you want.

The `[contextMenu]` directive is just a shorthand for listening to the `(contextmenu)` event and triggering the `ContextMenuService`.  So you can do this:

```
const item = {}; // get the item somehow
this.renderer.listen(el, 'contextmenu', (event) => this.onContextMenu(event, item));
```

`onContextMenu` is defined like [this](https://github.com/isaacplmann/ngx-contextmenu#context-menu-in-a-different-component)

**Comment by celestale** [comment]
```
<context-menu #basicMenu>
        <ng-template contextMenuItem let-item>1</ng-template>
        <ng-template contextMenuItem let-item>2</ng-template>
</context-menu>
<context-menu #secondMenu>
        <ng-template contextMenuItem let-item>1</ng-template>
        <ng-template contextMenuItem let-item>2</ng-template>
</context-menu>
```

```
@ViewChild('basicMenu') basicMenu: ContextMenuComponent;

onContextMenu($event: MouseEvent) {
        console.log('this.basicMenu', this.basicMenu);
        this.contextMenuService.show.next({
            contextMenu: this.basicMenu,
            event: $event,
            item: this.item
        });
        $event.preventDefault();
        $event.stopPropagation();
      }
```

Hi @isaacplmann, I tried to have multiple context-menu by setting them a `viewchild basicMenu`. Although it could catch the mouse event, but no contextmenu popping out.

However if I remove `contextMenu: this.basicMenu`, it will work fine. Did i emit the wrong value type to `contextMenu`?

PS: console.log shows a valid this.basicMenu

**Comment by DanielYKPan** [comment]
@celestale 
I am sorry, I got the same issue.
@celestale said he misplace the imports and it caused this issue. But I don't know how I misplace the imports and wonder how you fixed it.

**Comment by celestale** [comment]
@DanielYKPan Do you still have your code?
