### ISSUE TITLE
Context-menu do not open with angular 5.x

### ISSUE THREAD

**Issue by achyutgp** [isaacplmann/ngx-contextmenu#87]
Hi @isaacplmann, I recently updated my project to Angular 5.x. On inspect I see the context-menu under cdk-overlay-container, but it's not rendered on the screen. 

Below is the list of dependencies:
    ```"@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.1.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "ngx-contextmenu": "^4.1.2",
    "rxjs": "^5.5.6",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.19"```

Template:

```
<context-menu #menu>
  <ng-template contextMenuItem [subMenu]="thOpts">
    Thickness
  </ng-template>
  <context-menu #thOpts>
    <ng-template *ngFor="let thicknessOpt of thicknessOpts" contextMenuItem (execute)="customFunc(thicknessOpt.value)">
      {{thicknessOpt.name}}
    </ng-template>
  </context-menu>
</context-menu>
```

Trigger open of context-menu on click of custom button:

```
@ViewChild('menu') menu: ContextMenuComponent;

public onClick($event: any): void {
    this.contextMenuService.show.next({
      anchorElement: $event.target,
      contextMenu: this.menu,
      event: $event,
      item: null
    });
    $event.preventDefault();
    $event.stopPropagation();
  }
```

**Comment by isaacplmann** [comment]
Are you missing the css for the context menu?  When you inspect the `.cdk-overlay-pane` what are the css properties?

It should look like this:
![screen shot 2018-02-05 at 10 15 46 am](https://user-images.githubusercontent.com/861504/35811927-abeb8514-0a5d-11e8-964f-99a55a04447c.png)

**Comment by achyutgp** [comment]
@isaacplmann , Thought I'm unsure on how it worked before with ```v 1.3.5```, maybe the flow of implementation was incorrect.

Below is the method I followed with ```v 1.3.5```
![image](https://user-images.githubusercontent.com/28974455/35905978-f661d532-0c0e-11e8-85a0-6ff53bfac7ac.png)

Now, I moved ngx-context menu component's template and scripts to ```Component - A``` to make it work.

Thanks for your support!!!
