### ISSUE TITLE
[Dynamic actions] execute not fired

### ISSUE THREAD

**Issue by namnn** [isaacplmann/ngx-contextmenu#98]
Hi,

We were using the dynamic action context-menu. All the input binding like visible, enabled, divider work fine, but not the output execute.

When using ngFor for the actions, it does actually fires triggerExecute, but the function I bind never get called.

Fyi, I added an independent contextMenuItem (Test) and it triggers doAlert, unlike those inside the loop.

Please have a look. Thanks in advance.

Here is how we are using it:

```
<ul>
  <li *ngFor="let item of items;"
      [contextMenu]="contextMenu"
      [contextMenuSubject]="item">........</li>
</ul>
<context-menu #contextMenu>
  <ng-template
    *ngFor="let action of contextMenuActions"
    contextMenuItem let-item
    [visible]="action.visible" [enabled]="action.enabled"
    [divider]="action.divider" (execute)="doAlert('hello')"
  >
    {{action.text(item)}}
  </ng-template>
  <ng-template contextMenuItem (execute)="doAlert('hello')">
    Test
  </ng-template>
</context-menu>

**Comment by isaacplmann** [comment]
I don't see anything wrong with your template code. What does the ts file look like?

**Comment by namnn** [comment]
This is my component's ts

```
get contextMenuActions(): IMenuItem<IMatterDetailEntry>[] {
    return transformContextMenuActions([
      {
        execute: entry => {
          console.log(entry);
        },
        text: () => {
          return 'Test 1';
        },
        visible: () => true
      },
      {
        divider: true,
        visible: entry => true
      },
      {
        execute: entry => {
          console.log('hello world')
        },
        text: entry => 'Test 2',
        visible: entry => true
      }
    ]);
  }

doAlert(message): void {
    console.log(message);
  }
....
function transformContextMenuActions<T = {}>(actions: Partial<IMenuItem<T>>[]): IMenuItem<T>[] {
  const defaultMenuItem = {
    execute: () => {},
    divider: false,
    enabled: () => true,
    text: () => '',
    visible: () => true
  };
  return map(actions, (action: IMenuItem<T>) => ({ ...defaultMenuItem, ...action }));
}

**Comment by namnn** [comment]
I find that after reaching this statement, the execute function doesn't really get bubbled up to the component, but rather trigger close the contextMenu only
```
subscriptions.add(contextMenuContent.instance.execute.asObservable()
            .subscribe(function (executeEvent) { return _this.closeAllContextMenus(__assign({ eventType: 'execute' }, executeEvent));

**Comment by sherlock1982** [comment]
I had similar issue with execute not fired. Needed to call "setTimeout" after contextMenuActions was set for context menu. Try if it's your case. Though I must say it wasn't an issue in angular2-contextmenu.

**Comment by namnn** [comment]
@sherlock1982 thanks for sharing your experience. 

Can you please clarify more where to put the setTimeout? I bind the contextMenuActions via template.

Thanks in advance.
